 'use client';
import { useEffect,useRef,useState } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { cafeStory as copy, cafeAmbienceEnabled } from '@/lib/content';
export default function CafeEffects(){const audio=useRef<HTMLAudioElement|null>(null);const [playing,setPlaying]=useState(false);const [notice,setNotice]=useState('');
 useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const root=document.querySelector<HTMLElement>('.cafe-story');if(!root)return;const media=gsap.matchMedia();
 media.add({desktop:'(min-width:768px)',reduce:'(prefers-reduced-motion:reduce)'},context=>{const {desktop,reduce}=context.conditions!;if(reduce)return;
 let seen=true;try{seen=sessionStorage.getItem('hogs-cafe-arrival')==='1';sessionStorage.setItem('hogs-cafe-arrival','1');}catch{seen=false;}
 if(!seen)gsap.fromTo('.cs-chaos span',{opacity:.38,y:0,filter:'blur(2px)'},{opacity:0,y:-35,filter:'blur(10px)',duration:1.5,stagger:.08,ease:'power2.out'});
 gsap.utils.toArray<HTMLElement>('.cs-layer',root).forEach((layer,i)=>gsap.to(layer,{yPercent:(i+1)*(desktop?4:1.2),ease:'none',scrollTrigger:{trigger:'.cs-arrival',start:'top top',end:'bottom top',scrub:1.2}}));
 gsap.utils.toArray<HTMLElement>('[data-cafe-reveal]',root).forEach(el=>gsap.from(el,{y:24,duration:1, ease:'power2.out',scrollTrigger:{trigger:el,start:'top 88%',toggleActions:'play none none reverse'}}));
 if(desktop){root.classList.add('cs-pinned');const track=root.querySelector<HTMLElement>('.cs-terrace-track')!;const viewport=root.querySelector<HTMLElement>('.cs-terrace-viewport')!;gsap.to(track,{x:()=>-(track.scrollWidth-viewport.clientWidth),ease:'none',scrollTrigger:{trigger:'.cs-terrace',start:'top top',end:()=>'+='+(track.scrollWidth-viewport.clientWidth),pin:true,scrub:1.2,invalidateOnRefresh:true}});gsap.utils.toArray<HTMLElement>('.cs-terrace-photo img',root).forEach(img=>gsap.fromTo(img,{scale:1.08},{scale:1.02,ease:'none',scrollTrigger:{trigger:'.cs-terrace',start:'top top',end:'bottom top',scrub:1}}));}
 const dusk=gsap.timeline({scrollTrigger:{trigger:'.cs-dusk',start:'top 75%',end:'bottom 25%',scrub:1}});dusk.to(root,{'--cs-bg':'#20252e',duration:1},0).to(root,{'--cs-bg':'#140e0b',duration:1},1);[1,2,3].forEach((i)=>dusk.fromTo(`.cs-dusk-frame-${i}`,{opacity:0},{opacity:1,duration:.7},(i-1)*.6));
 const move=(event:PointerEvent)=>{if(!desktop||event.pointerType==='touch')return;root.style.setProperty('--light-x',`${event.clientX}px`);root.style.setProperty('--light-y',`${event.clientY}px`);const x=event.clientX/innerWidth-.5,y=event.clientY/innerHeight-.5;gsap.to('.cs-depth',{rotateY:x*1.5,rotateX:-y,duration:1});const card=(event.target as Element).closest<HTMLElement>('[data-cafe-tilt]');if(card){const box=card.getBoundingClientRect();gsap.to(card,{rotateY:(event.clientX-box.left)/box.width*8-4,rotateX:4-(event.clientY-box.top)/box.height*8,duration:.7,transformPerspective:900});}};
 const reset=(event:PointerEvent)=>{const card=(event.target as Element).closest<HTMLElement>('[data-cafe-tilt]');if(card&&!card.contains(event.relatedTarget as Node))gsap.to(card,{rotateX:0,rotateY:0,duration:.8});};root.addEventListener('pointermove',move);root.addEventListener('pointerout',reset);return()=>{root.removeEventListener('pointermove',move);root.removeEventListener('pointerout',reset);root.style.removeProperty('--cs-bg');root.classList.remove('cs-pinned');};},root);
 const refresh=()=>ScrollTrigger.refresh();document.fonts.ready.then(refresh);window.addEventListener('load',refresh);const imageLoad=(event:Event)=>{if(event.target instanceof HTMLImageElement)refresh();};root.addEventListener('load',imageLoad,true);return()=>{media.revert();root.removeEventListener('load',imageLoad,true);window.removeEventListener('load',refresh);audio.current?.pause();};},[]);
 const toggle=async()=>{if(!cafeAmbienceEnabled){setNotice(copy.ambience.missing);return;}if(playing){audio.current?.pause();setPlaying(false);return;}if(!audio.current){audio.current=new Audio(copy.ambience.path);audio.current.loop=true;audio.current.volume=.16;}try{await audio.current.play();setPlaying(true);setNotice('');}catch{setNotice(copy.ambience.missing);setPlaying(false);}};
 return <><div className="cs-cursor-light" aria-hidden="true"/>{cafeAmbienceEnabled&&<div className="cs-ambience"><button type="button" aria-pressed={playing} onClick={()=>void toggle()}>{playing?copy.ambience.on:copy.ambience.off}</button>{notice&&<p role="status">{notice}</p>}</div>}</>;
}
