import Link from 'next/link';
import Image from 'next/image';
import { SITE, cafeHours, content, footerLinks, RAZORPAY_SUPPORT_URL } from '@/lib/content';
import FooterMap from './FooterMap';
import Icon from '@/components/ui/Icon';
import InstagramLink from '@/components/ui/InstagramLink';
import FooterBookLink from '@/components/ui/FooterBookLink';
import { packageMeta } from '@/lib/packageMeta';
const razorpayBadge = <Image src="/images/footer/razorpay-support.webp" alt="Support HOGS – secure payments by Razorpay" width={480} height={102} sizes="(max-width: 700px) 160px, 200px" loading="lazy" />;
export default function Footer() { return <><footer id="footer" className="footer"><div className="footer-top"><div><p>{content.ui.footer.heading[0]}<br /><em>{content.ui.footer.heading[1]}</em></p></div><div className="footer-contact"><span className="eyebrow">MANALI, HIMACHAL PRADESH</span><a href={`mailto:${content.email}`}>{content.email}</a><a href={`tel:+${content.whatsapp}`}>{content.phone}</a><InstagramLink href={content.instagram} label="HOGS on Instagram" /><span className="footer-cafe-hours"><strong>Cafe DO NTHNG</strong> {cafeHours.text}</span></div></div><div className="footer-cols"><div className="footer-brand"><Link className="footer-logo" href="/" prefetch={false}><Image src={SITE.logo.src} alt={SITE.logo.alt} width={SITE.logo.width} height={SITE.logo.height} loading="lazy" unoptimized /></Link><p>A little closer to nature. A little closer to yourself. Mountain stays, a cafe and slow journeys in Manali.</p><address className="footer-address"><Icon name="pin" size={18} /><span>{SITE.address.text}</span></address></div><div className="footer-nav-cols"><nav className="footer-sitemap" aria-label="Footer navigation"><span className="eyebrow">EXPLORE</span>{footerLinks.map(link=>link.href==='/book'?<FooterBookLink key={link.href} href={link.href} title={link.title}/>:<Link key={link.href} href={link.href} prefetch={link.href==='/'?false:undefined}>{link.title}</Link>)}</nav><nav className="footer-sitemap footer-journeys" aria-label="Manali packages"><span className="eyebrow">MANALI PACKAGES</span>{packageMeta.map(item=><Link key={item.slug} href={`/packages/${item.slug}`}>{item.name}</Link>)}</nav></div><div className="footer-find"><span className="eyebrow">FIND US</span><FooterMap /></div></div><div className="footer-links">{content.policies.map(policy=><Link key={policy.slug} href={`/${policy.slug}`}>{policy.title}</Link>)}<Link href="/credits">Credits</Link></div><div className="footer-pay">{RAZORPAY_SUPPORT_URL ? <a href={RAZORPAY_SUPPORT_URL} target="_blank" rel="noopener noreferrer" aria-label="Support HOGS – secure payments by Razorpay (opens in a new tab)">{razorpayBadge}</a> : razorpayBadge}</div><div className="footer-bottom"><span>© {new Date().getFullYear()} HOGS — Of Himalayan Homes.</span><div className="footer-bottom-end"><span>{content.ui.footer.credit}</span><span className="footer-made">Made with <span aria-hidden="true">❤️</span><span className="sr-only">love</span> by <a href="https://velotixtech.com" target="_blank" rel="noopener noreferrer" aria-label="Velotix Tech website (opens in a new tab)">Velotix Tech</a></span></div></div><div className="footer-wordmark" aria-hidden="true">HOGS</div></footer><a className="mobile-whatsapp" href={`https://wa.me/${content.whatsapp}`} target="_blank" rel="noopener noreferrer" aria-label="Chat with HOGS on WhatsApp"><Icon name="chat" size={25} /></a></>; }
