'use client';
import Image from 'next/image';
import { useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { content } from '@/lib/content';
import Icon from '@/components/ui/Icon';
function StayCard({ property, index }: { property: typeof content.properties[number]; index: number }) {
  const [slide, setSlide] = useState(0); const reduced = useReducedMotion();
  const isCafe = property.type === 'cafe';
  const choose = () => { window.dispatchEvent(new CustomEvent('hogs:property', { detail: property.name })); };
  return <article className="stay-card" id={property.id}><div className="stay-visual">{property.images.map((image,i)=><Image key={image.src} className={i===slide?'stay-img is-active':'stay-img'} src={image.src} alt={i===slide?image.alt:''} aria-hidden={i!==slide} fill sizes="100vw" style={{objectPosition:image.position}} />)}{property.images.length>1&&<div className="slider-controls"><button className="icon-button" aria-label={`Previous ${property.name} photo`} onClick={()=>setSlide((slide+property.images.length-1)%property.images.length)}><span aria-hidden="true">←</span></button><span aria-live="polite">0{slide+1} / 0{property.images.length}</span><button className="icon-button" aria-label={`Next ${property.name} photo`} onClick={()=>setSlide((slide+1)%property.images.length)}><Icon /></button></div>}</div><div className="stay-copy"><p className="eyebrow">0{index+1} / {isCafe ? content.ui.stays.cafeLabel : content.ui.stays.cardEyebrow}</p><h3>{property.name}</h3><p className="subtitle">{property.subtitle}</p><p className="description">{property.description}</p><div className="chips">{property.highlights.map(chip=><span className="chip" key={chip}>{chip}</span>)}</div>{isCafe ? <div className="cafe-ctas"><a className="text-link" href="#footer">{content.ui.stays.cafeCta} <Icon /></a><a className="text-link" href={property.mapUrl || `mailto:${content.email}`} target={property.mapUrl ? '_blank' : undefined} rel={property.mapUrl ? 'noopener noreferrer' : undefined}>{content.ui.stays.cafeDirections} <Icon name="pin" /></a></div> : <motion.a whileHover={reduced ? undefined : { x: 4 }} className="text-link" href="#form" onClick={choose}>{content.ui.stays.cta} <Icon /></motion.a>}</div></article>;
}
export default function Stays() { return <section id="our-stay" className="section stays"><div className="section-topline"><p className="eyebrow">{content.ui.stays.eyebrow}</p><span className="section-index">{content.ui.stays.index}</span></div><div className="section-heading"><h2>{content.ui.stays.heading[0]}<br /><em>{content.ui.stays.heading[1]}</em></h2><p>{content.staysIntro}</p></div><div className="stay-track">{content.properties.map((property,index)=><StayCard key={property.id} property={property} index={index} />)}</div></section>; }

