// GENERATED by scripts/optimize-about-images.mjs (npm run images:about). Do not edit by hand.
export type AboutImage = { id: string; src: string; srcSet: { width: number; src: string }[]; width: number; height: number; alt: string; caption: string; position: string; blurDataURL: string };
export const aboutImages = {
  "building": {
    "id": "hogs-manali-building-exterior-hogs-gate-misty-mountains",
    "src": "/images/about/hogs-manali-building-exterior-hogs-gate-misty-mountains-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/about/hogs-manali-building-exterior-hogs-gate-misty-mountains-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/about/hogs-manali-building-exterior-hogs-gate-misty-mountains-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/about/hogs-manali-building-exterior-hogs-gate-misty-mountains-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "HOGS Panorama building and entrance gate in Manali with misty mountains",
    "caption": "The HOGS gate and the building, wrapped in mountain mist",
    "position": "center 50%",
    "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZQCdACG5L+ytmZqCpOanl7AA/lK9DmxLIWFJqIwEfQMYhHdUZGq4QEKnGLS2DwCPtLX2kzzqsvgtsmmrlCqKaRS6B29sYTTTMhLLlijrFYEWn7AErj06ktxL/HJdZppPNiZDU6vdE0AA"
  },
  "gazal": {
    "id": "hogs-founder-gazal-cafe-do-nthng-terrace-manali",
    "src": "/images/about/hogs-founder-gazal-cafe-do-nthng-terrace-manali-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/about/hogs-founder-gazal-cafe-do-nthng-terrace-manali-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/about/hogs-founder-gazal-cafe-do-nthng-terrace-manali-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/about/hogs-founder-gazal-cafe-do-nthng-terrace-manali-1920.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "Gazal, co-founder of HOGS, on the Cafe DO NTHNG terrace in Manali beside the House of Gaz and Saloni mural",
    "caption": "Gazal",
    "position": "center 58%",
    "blurDataURL": "data:image/webp;base64,UklGRg4BAABXRUJQVlA4IAIBAABwBgCdASoYACQAPu1wq1KppiOipWsxMB2JZQDDsbDCMtDJy8yR5hq7KdCV1OpyDswy8T7kxGHY+PluJQAA/vJJ9tXJc3kWsgnXoTdhxULSyIZI2tq2eJBcqNQF7YNFQ9emrNELMm4dUgoGTyIiTKvBUdnfq/D//gZgATd8ydMaMVEMeFFgaIOZxvS/c34g9BhwZH3u3OmeqGo/NAEZH9UFmXQY8gmz9lDFzUw6jD2ovQyPMFYA75d/z/mWTe+p22BwVlYPtQ+C3a6sm/b6wrYLSdjE3D2tyMCo13B42+Nkibf5oZA6Fs1VLRQaPx7HjJMYIm216EQfj5YTV/mbO1HaoAA="
  },
  "saloni": {
    "id": "hogs-founder-saloni-cafe-do-nthng-terrace-manali",
    "src": "/images/about/hogs-founder-saloni-cafe-do-nthng-terrace-manali-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/about/hogs-founder-saloni-cafe-do-nthng-terrace-manali-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/about/hogs-founder-saloni-cafe-do-nthng-terrace-manali-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/about/hogs-founder-saloni-cafe-do-nthng-terrace-manali-1920.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "Saloni, co-founder of HOGS, at the Cafe DO NTHNG terrace in Manali",
    "caption": "Saloni",
    "position": "center 55%",
    "blurDataURL": "data:image/webp;base64,UklGRggBAABXRUJQVlA4IPwAAACQBgCdASoYACQAPu1qqlAppiOiqrgMATAdiWUAwgsyuZ06LoT0b7Kff5eB0jOVaHJxPxCHpI3HpPjrTbuAAP7uWrDSLw3nLIxj9TPIMz+k/OGlr/HPEm26wx68BF3UVQNe8KV0+rWyv4k4tcALSAfxxTjdBoxua4HK8/sZQXhBRD06+7vThSzebiVwmS7XeMh8EZgxERkET4NBucdCSTRM3F1HLOLe+/2QdHMlf8/p66ajByuBH9JFYcc/sg60OMF+QMtgt1VcKpZGlh7CeEKooYr1k/hzg9U+jF/JRA/TB2r4DuhugItGDtgY1u9Gxbju9w45UeQfDoyIAAA="
  },
  "friends": {
    "id": "hogs-founders-gazal-saloni-with-friends-hogs-sign-manali",
    "src": "/images/about/hogs-founders-gazal-saloni-with-friends-hogs-sign-manali-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/about/hogs-founders-gazal-saloni-with-friends-hogs-sign-manali-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/about/hogs-founders-gazal-saloni-with-friends-hogs-sign-manali-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/about/hogs-founders-gazal-saloni-with-friends-hogs-sign-manali-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Gazal and Saloni, founders of HOGS, with friends beside the HOGS sign in Manali",
    "caption": "Gazal & Saloni with friends at HOGS.",
    "position": "center 50%",
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADQAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JQBWAApQMDqp7OQExsgAA/aFx3WpPZqzB4VZvKfeqM/9xj5PHxLKX5SSJhm11s+nHf0KBHygPO67GUPWH2eeI8faQazC08nsbpeDJihAHKal+MY1jFMciXYsr55ECpwC+WQqspciSdbYKFXtGHmkvpB1gTkK/WaBUNAAA"
  }
} as const satisfies Record<string, AboutImage>;
