// AUTO-GENERATED by scripts/optimize-cafe-images.mjs from scripts/cafe-images.json. Do not edit by hand; run `npm run images:cafe`.
export type CafeCategory = 'terrace' | 'exterior' | 'food-drinks' | 'live-music' | 'ambience-night' | 'team' | 'guests' | 'behind-the-bar';
export type CafeImage = {
  id: string; category: CafeCategory; /** 1280px WebP (or the widest available). */ src: string; srcSet: { width: number; src: string }[];
  width: number; height: number; alt: string; caption: string; /** CSS object-position for cropped (cover) uses. */ position: string; featured: boolean; blurDataURL: string;
};
export type PanoramaCoverImage = Omit<CafeImage, 'category'> & { category: string };
export const cafeOgImage = {"src":"/images/cafe-do-nthng/og/cafe-do-nthng-manali-mountain-terrace-prayer-flags-cover-og-1200x630.jpg","width":1200,"height":630};
export const panoramaOgImage = {"src":"/images/hogs-panorama/og/hogs-panorama-manali-cozy-bedroom-mountain-view-og-1200x630.jpg","width":1200,"height":630};
export const cafeImageList: CafeImage[] = [
  {
    "id": "cafe-do-nthng-manali-mountain-terrace-prayer-flags-cover",
    "category": "terrace",
    "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-mountain-terrace-prayer-flags-cover-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-mountain-terrace-prayer-flags-cover-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-mountain-terrace-prayer-flags-cover-1280.webp"
      },
      {
        "width": 1448,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-mountain-terrace-prayer-flags-cover-1448.webp"
      }
    ],
    "width": 1448,
    "height": 1086,
    "alt": "Sunny terrace at Cafe DO NTHNG in Manali, with cream wicker chairs, strings of prayer flags and fairy lights, a wooden swing and forested mountains behind",
    "caption": "THE TERRACE, FACING THE PEAKS",
    "position": "50% 55%",
    "featured": true,
    "blurDataURL": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAAAwBQCdASoYABIAPu1qr1AppaSiqAqpMB2JaACdOUFXOeAAdIB+S+2DSwYfDuKNCVGPAAD+WAyz+zyrXYtfNTbAcTIbEAjvAqDaAe+v7AYt/i+B3BIVii0uM3+5Cem+W+q4NStd2AlAKnTxOlnLARzXUgYUyaLZqbtC3dJYXeJ0+b2f535gOsKZdywvv5JlUz80QPa73NxRnHT5uZVICEqJOU8FkMX7QfhZkwwYRVa40QehwAAAAA=="
  },
  {
    "id": "cafe-do-nthng-manali-terrace-motorbike-mural-wicker-seating",
    "category": "terrace",
    "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-motorbike-mural-wicker-seating-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-motorbike-mural-wicker-seating-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-motorbike-mural-wicker-seating-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-motorbike-mural-wicker-seating-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Cafe DO NTHNG terrace in Manali, with a painted mural of a mountain and a motorbike, and wicker chairs around glass tables",
    "caption": "A MURAL FOR THE RIDERS",
    "position": "50% 45%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JQBOmUAA9reds8UE6B8oAAP2ssrNG9lORob8CxNK4hQhfmvlE425XNgley4fy0Nzws/lFYGAb73tqttY8R9PaB4CSMEcTzhdO2KBwhXurHHLtpFrNwajPIVO8QrKVCRKD//DdPWq3aHUCIq0PTqgQgAA="
  },
  {
    "id": "cafe-do-nthng-manali-egg-chair-mural-terrace-seating",
    "category": "terrace",
    "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-egg-chair-mural-terrace-seating-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-egg-chair-mural-terrace-seating-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-egg-chair-mural-terrace-seating-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-egg-chair-mural-terrace-seating-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "A hanging egg chair beside a hand-painted mountain mural and wicker chairs on the terrace at Cafe DO NTHNG, Manali",
    "caption": "THE EGG CHAIR, BESIDE THE MURAL",
    "position": "50% 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQBOmUABMNJXcDY0lWsMTls9Q0ADL+U76GYxbu+Vef9oUGb6Rdkt97FbiB/LRaz4DeKBR1buh8vVJ7gObIpv1DfDNG5DQTGBn0PXrGmL8YTuJsJfoSioloATLy2J4w923knMYC8fGVs4Ns5U8C85au5wAAA=="
  },
  {
    "id": "cafe-do-nthng-manali-egg-chair-forest-view",
    "category": "terrace",
    "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-egg-chair-forest-view-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-egg-chair-forest-view-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-egg-chair-forest-view-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-egg-chair-forest-view-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "A hanging egg chair and wicker seating on the Cafe DO NTHNG terrace in Manali, framed by green trees and the valley",
    "caption": "THE EGG CHAIR, FACING THE FOREST",
    "position": "50% 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZQC7AB6yb/FWtfKDMaT7pWHIAM49mlE6oQu7XCG04riJJNEA0jcFCARAT5RzeU4d/4XlykVw/i0aF+MLRinESoINMxwd2CJbnXVYHkUk9hSb7fp9sWFWdwyxOnTiIgarCCE9AsYAAA=="
  },
  {
    "id": "cafe-do-nthng-manali-terrace-walkway-prayer-flags-tables",
    "category": "terrace",
    "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-walkway-prayer-flags-tables-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-walkway-prayer-flags-tables-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-walkway-prayer-flags-tables-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "A glass-railed walkway on the Cafe DO NTHNG terrace in Manali, with tables, prayer flags and a mural among green trees",
    "caption": "THE LONG WAY ALONG THE TERRACE",
    "position": "50% 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRvYAAABXRUJQVlA4IOoAAABQBgCdASoYACQAPu1urlIppiQiqrgIATAdiWcAvKQhkg9mkSOFPovmRnzNwyxqQiXXK6P6/OFsjAN0yADNnvd+d2BTqCyX1Van6XXNfngEr/ExpEeTSscdPXlmM24L/dwehjQM/VLcf5YCrfr4QKbxY1YO0CO9uHO6nr82yO7aGW/e684ri/MPbU6Bf+hbrD45dGaoFWlDwrTrbqGGdEUHM2G9Y2SBcJS84PEGMnprWUuzHz238wBa5C3sghFRKQBuWDiLEXrx/XwvHpvoa3YUcUyAiyIXdkEvFn7YOhhh3+CYk681GCZAAAA="
  },
  {
    "id": "cafe-do-nthng-manali-sunny-terrace-mural-prayer-flags",
    "category": "terrace",
    "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-sunny-terrace-mural-prayer-flags-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-sunny-terrace-mural-prayer-flags-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-sunny-terrace-mural-prayer-flags-1280.webp"
      },
      {
        "width": 1536,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-sunny-terrace-mural-prayer-flags-1536.webp"
      }
    ],
    "width": 1536,
    "height": 1024,
    "alt": "Sunny terrace at Cafe DO NTHNG, Manali, with wicker chairs, prayer flags, a mountain mural and valley views",
    "caption": "THE TERRACE, IN FULL SUN",
    "position": "65% 50%",
    "featured": true,
    "blurDataURL": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZgCdIExgxwItQvM7lOm2LAD923JpGplpxf46ZeB6IjPgPRxtEX7cM/AAYbmgA8MhEWs0EWfMCP/Yk7ScQkCYToHvslBZlIeKKE+3ezA9xwyhO3V46aSq62zWSKeQ3skqbX7SDE7VbnERxQQUMqq3Ae8LFuQI28lqWKPkU+MmVeDUK2pG9B4IYDj3vW7XXNCM4gw1Niq0MAAA"
  },
  {
    "id": "cafe-do-nthng-manali-terrace-lanterns-prayer-flags-dusk",
    "category": "terrace",
    "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-lanterns-prayer-flags-dusk-1024.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-lanterns-prayer-flags-dusk-640.webp"
      },
      {
        "width": 1024,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-lanterns-prayer-flags-dusk-1024.webp"
      }
    ],
    "width": 1024,
    "height": 1536,
    "alt": "Cafe DO NTHNG terrace in Manali at dusk, with glowing bamboo lanterns, prayer flags and mountain views",
    "caption": "THE TERRACE AT BLUE HOUR",
    "position": "50% 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRloBAABXRUJQVlA4IE4BAAAwBwCdASoYACQAPu1kqE8ppSOiKqwBMB2JbACdMzL/9YAKBSdENfyR9bz2KaiK0jZb/dJ55qDC+ZuoPz7nv0W9ugAA/c35G2VzyiKIdZPzbfGJMGWde80BVhW+CBO5FsxJMZBMa5mD2g2kkpSIIVAad2SaxP/G6ypNXJxcA0SgV0nftirhCJa48geFpQwZALrPKX45vpmh5AdMyX0v8oEO6lULgWOOy0tKGyud0nI85CKBIK8szvHI/7EGhr97A1T6pf6xJo30xQJlZLGMvk+Vxhjctf2XuEhpOSxPH6OZ7ffGeZXK1sQNnJvhdlMNqMndYFnBJmU6wEwXNdAUpr/8eGe7QGXZej1xSTblWJcc01dakOQkvBxqPQ5YlcB2UQnwlo2xi8JPaNVczH1CwlYC1tPwM8kzdqR9SUo/K6cY4XQHPI5NAsAySrkQgAAA"
  },
  {
    "id": "cafe-do-nthng-manali-building-exterior-hogs-gate",
    "category": "exterior",
    "src": "/images/cafe-do-nthng/exterior/cafe-do-nthng-manali-building-exterior-hogs-gate-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/exterior/cafe-do-nthng-manali-building-exterior-hogs-gate-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/exterior/cafe-do-nthng-manali-building-exterior-hogs-gate-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/exterior/cafe-do-nthng-manali-building-exterior-hogs-gate-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "The HOGS building and its wooden gateway in Manali on a misty day, with cloud-hung mountains behind",
    "caption": "THE HOGS GATE, ON A MISTY DAY",
    "position": "center 55%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwBACdASoYABAAPu1kqk4ppaQiMAgBMB2JZQCdAB6XiwGqDGBPwTvF3/wA/dJD4l2PhallItCrtYoj7CZYhVHxurc3TMjjqqUigtCgZBX9Kd2Xhy7eeJUsFfFR9205lwsjY3ume1UWdh/YQ9naOQjWz14fIACdFAAAAA=="
  },
  {
    "id": "cafe-do-nthng-manali-terrace-mountain-view",
    "category": "terrace",
    "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-mountain-view-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-mountain-view-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-mountain-view-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-mountain-view-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "The terrace at Cafe DO NTHNG in Manali, with cream wicker chairs, strings of prayer flags and forested mountains beyond",
    "caption": "THE TERRACE, FACING THE MOUNTAINS",
    "position": "center 50%",
    "featured": true,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZQCdAB6MGVNDzPxG8du3mPXFAAD+xGEYeSWi/kclQ7Edb+iHBQpTvDi6h0aPBZ9HLt5bpPNbC0bK80AKzu7bsjzbEXkyzb6dQz0J6Rwz/dxOWi3Crw+nP1EycbArVEa7qXCwkfmgMeLHB7ngcMZoBg1D6o9WgAA="
  },
  {
    "id": "cafe-do-nthng-manali-terrace-mural-swing",
    "category": "terrace",
    "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-mural-swing-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-mural-swing-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-mural-swing-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-mural-swing-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Cafe DO NTHNG's terrace in Manali, with a painted mountain mural, a wooden swing and wicker seating facing the valley",
    "caption": "A MURAL, A SWING, A VALLEY",
    "position": "center 50%",
    "featured": true,
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBACdASoYABAAPu1iqU2ppaQiMAgBMB2JYwCdACIeoDXS5CSfLDi9gIAA/tRp3z8zXBK3Jg4skqwFyYW27aAHCTrhhnlmA1c4cE1K2BUMnsS54QnFBiuD1cRedrXrs1v8OO+boRGyMD5Fh7kr4BOchDjGit2r2qYbT4faXY4TCjCjzQsLHDXwAAA="
  },
  {
    "id": "cafe-do-nthng-manali-swing-chair-mountain-sky",
    "category": "terrace",
    "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-swing-chair-mountain-sky-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-swing-chair-mountain-sky-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-swing-chair-mountain-sky-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "A hanging wicker swing chair with blue cushions against cloudy mountains at Cafe DO NTHNG in Manali",
    "caption": "A SWING UNDER THE CLOUDS",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAADwBQCdASoYACQAPu1wsFOppiQipWgBMB2JQAAUqJpGWQIrVeGY7KvP/H4+vRJUu0lEIVISmga4AAD3B+0XE+dBKexbT+v8f3lsKrF6QT/Ox1N0X+kOEgE3c53eunFgwifRgDA4nMnfGpZFPwWzjB3FxHu+IQWM99bsKOm1wPojebG8Vr42znpx4Q4jrkz+TNtGF68jAn6UkC5xbHEETZhLY/uvxgTswRzlvGoFkTFob47yWAYUAA=="
  },
  {
    "id": "cafe-do-nthng-manali-terrace-chai-prayer-flags",
    "category": "terrace",
    "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-chai-prayer-flags-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-chai-prayer-flags-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/terrace/cafe-do-nthng-manali-terrace-chai-prayer-flags-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "Two guests sipping chai at a wicker table on the Cafe DO NTHNG terrace in Manali, under prayer flags with mountains behind",
    "caption": "CHAI UNDER THE PRAYER FLAGS",
    "position": "center 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRhQBAABXRUJQVlA4IAgBAADQBgCdASoYACQAPu1oqU8ppiOiKqwBMB2JQBerZi8Vzul7lva2lYvxWGnrVmK4TdilQU/JncrFbd9T3tCzvKAA/F3fzVABcnmjnGzSSEz39VtnP/AReHeDdHWIk8tIP1uHDGrXxaYPWcoAjDIBEh1CzYuYjkaLm8qdzzLuZ+EYs69gD2tg4FiJIe36cNsruZ7HHFbeTeonRLP6CW/0fnlHoptco8SgsI6VAjY5dTAbgqbRwnYk2CgY40hYujtTHQk9nfVTvWycgNpz1AHju//9+4DJnJHDwzR94q4LbF8nd8QrP8W2zlkztAeQZkLCAMho3FghHvoUlhJYEqHiomh7Isamt9wAAAA="
  },
  {
    "id": "cafe-do-nthng-manali-latte-art-coffee",
    "category": "food-drinks",
    "src": "/images/cafe-do-nthng/food-drinks/cafe-do-nthng-manali-latte-art-coffee-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/food-drinks/cafe-do-nthng-manali-latte-art-coffee-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/food-drinks/cafe-do-nthng-manali-latte-art-coffee-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "Overhead view of a cappuccino with leaf-shaped latte art on a teal saucer with a small biscuit, at Cafe DO NTHNG in Manali",
    "caption": "A CUP WITH A LITTLE ART",
    "position": "center 45%",
    "featured": true,
    "blurDataURL": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAAAwBgCdASoYACQAPu1mq1GppSOrKrgKAWAdiUAZ3Yw2L9basxBlWnP5kJa/+PIC0VIkgJ4yNqWYdFwAAP6B1SD6Zvn6EYob8T9T+O29E+iCyOTcXHcBhuQxKqcf7E6AXyNwneEdBCi6RWwjtxTwzFtEa1HNECLjQW7SmHxFvDXLPzD1DBbKgyGjl1UmLDNwT7ggM+xR5su8uoe4lk/UZ9tPfmVtvdjdhugAAA=="
  },
  {
    "id": "cafe-do-nthng-manali-green-mocktail-prayer-flags",
    "category": "food-drinks",
    "src": "/images/cafe-do-nthng/food-drinks/cafe-do-nthng-manali-green-mocktail-prayer-flags-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/food-drinks/cafe-do-nthng-manali-green-mocktail-prayer-flags-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/food-drinks/cafe-do-nthng-manali-green-mocktail-prayer-flags-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "A green mint mocktail with a pink paper umbrella, prayer flags softly blurred behind, at Cafe DO NTHNG in Manali",
    "caption": "MINT, ICE, PRAYER FLAGS",
    "position": "center 60%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRh4BAABXRUJQVlA4IBIBAACwBwCdASoYACQAPuleqU2pJSQiNVgIASAdCWQAuyE9Capd4yHhQuZdgQcyuAelvuNqboQ4xr/nRVmO16REHrVALYe8LFsAAP7x0+XLvVRKxOVcNBQ1CCR9yKVfytHKBOi5ZXaeC9IZTveX6P5mHe22giCN5wPWN+k0TAPK26pKV+nanQ6m9XqeXJYygZxUDcbeRclswLrwUtPCu+4r0qNlZr/ZuCihaj5R/8OFyOsHPxPp3EFgmwtHq2AmGD0Ct3Ui3OSdr4N/IZhwLOdGRJAJ71u/uyDisdNku2b9ef4sqkWJDgrXVaX+HyYz3L6JpJMYc5ZBqbcv3qMdP9cA55TjWQfTyEN+j5Di3FMy2SBAJAAA"
  },
  {
    "id": "cafe-do-nthng-manali-berry-mocktail",
    "category": "food-drinks",
    "src": "/images/cafe-do-nthng/food-drinks/cafe-do-nthng-manali-berry-mocktail-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/food-drinks/cafe-do-nthng-manali-berry-mocktail-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/food-drinks/cafe-do-nthng-manali-berry-mocktail-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "A red berry and mint mocktail with a pink paper umbrella and a yellow straw at Cafe DO NTHNG in Manali",
    "caption": "A BERRY MOCKTAIL",
    "position": "center 45%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAwBQCdASoYACQAPu1eqU4ppKOiMBqqqTAdiUAXYAL7gQiFy/6HPxDTV/XTtEhZDvmoEAD+0PoqV4fgZjsb1zGCVuUwSGESuavGrzTC5SPQQ6xDDPCE4pCXTF5ea86NydURQwOg7iScoOK2iV5VvPvdWVMZnVdYHnztNi15ZgoYPEcDJ/jQgSDpqQQMAAAA"
  },
  {
    "id": "cafe-do-nthng-manali-orange-citrus-cooler-mountains",
    "category": "food-drinks",
    "src": "/images/cafe-do-nthng/food-drinks/cafe-do-nthng-manali-orange-citrus-cooler-mountains-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/food-drinks/cafe-do-nthng-manali-orange-citrus-cooler-mountains-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/food-drinks/cafe-do-nthng-manali-orange-citrus-cooler-mountains-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "A tall citrus cooler with orange slices and a paper umbrella, with mountains behind it, at Cafe DO NTHNG in Manali",
    "caption": "A CITRUS COOLER, MOUNTAIN SIDE",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRuAAAABXRUJQVlA4INQAAADwBQCdASoYACQAPuVcpU2pJSOiOrM4ASAciWwAtRuDwNnVgMapkyLMFQUIgrYIldKsMIOQqBCr6ADlB6Af9cISrYWhZpWjU4Wr9ROa1Kz1bamZ4BJt704+vUjM0dz77rnC+pG6hJ41E8sKnVTYbVf/Zu5Mr269XUdtn4pm2i51pLzvVzqbj4S5FU/pwFdpxMJo/wKfvgxpwoI+9m9GYpuh7lyFMndNij7Zb/iN6qkVweNCGySXE1em9p/DzC8DEbvY/S65p/8vWZRUXDjLY7BJuAAAAA=="
  },
  {
    "id": "cafe-do-nthng-manali-live-acoustic-guitar-session",
    "category": "live-music",
    "src": "/images/cafe-do-nthng/live-music/cafe-do-nthng-manali-live-acoustic-guitar-session-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/live-music/cafe-do-nthng-manali-live-acoustic-guitar-session-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/live-music/cafe-do-nthng-manali-live-acoustic-guitar-session-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "A musician in a denim jacket playing acoustic guitar at an evening session at Cafe DO NTHNG in Manali, with prayer flags overhead",
    "caption": "AN EVENING SESSION",
    "position": "center 40%",
    "featured": true,
    "blurDataURL": "data:image/webp;base64,UklGRu4AAABXRUJQVlA4IOIAAABwBgCdASoYACQAPulYpE2pJKMiNVgMASAdCUAX/YLTPv9GF5C4INZD9r+OZpElP+ejwPrcxdw6atz+rAAA/vMC4lgtHp8hHldyygP1/iI8yQGX4dOJWzq8eaVOJUPZkEgHbatO+Zu+3UrNOPtkwhrLvNIf6wf5vC/damRdPkH5fq/LOmw/C7EUSjzBuf5b7nRUxKC8DgsDHNtM/BfNIOQX5O0/LXTzLE0JKL8+IPQCrLdXt5inLoZmJqK5lMJFGER6SQFphwVhVjDHRnE84vHiwPMxcGCkxX7b1fCF6hmrJ8AA"
  },
  {
    "id": "cafe-do-nthng-manali-live-singer-guitar-mic-night",
    "category": "live-music",
    "src": "/images/cafe-do-nthng/live-music/cafe-do-nthng-manali-live-singer-guitar-mic-night-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/live-music/cafe-do-nthng-manali-live-singer-guitar-mic-night-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/live-music/cafe-do-nthng-manali-live-singer-guitar-mic-night-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/live-music/cafe-do-nthng-manali-live-singer-guitar-mic-night-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "A singer with an acoustic guitar and a microphone performing at night at Cafe DO NTHNG in Manali",
    "caption": "LIVE, AFTER DARK",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAwBACdASoYABAAPu1iqU2ppaQiMAgBMB2JZQDG9CHrTw5xjHFY2VJ+6qAA/vKfTzadM9G8Og5meEFr0tlXYpN2t0q8t79BW2kAXc51Pc/hJtY+LHAaD5MemUk+naZSBOcGwzCk+iFVCkctclFu2l8zCMWprrrgAAA="
  },
  {
    "id": "cafe-do-nthng-manali-neon-sign-night-entrance",
    "category": "ambience-night",
    "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-neon-sign-night-entrance-1272.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-neon-sign-night-entrance-640.webp"
      },
      {
        "width": 1272,
        "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-neon-sign-night-entrance-1272.webp"
      }
    ],
    "width": 1272,
    "height": 1189,
    "alt": "Cafe DO NTHNG at night in Manali, its neon sign glowing above a stone entrance with terrace seating and potted plants",
    "caption": "THE NEON SIGN, AFTER DARK",
    "position": "center 46%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAAAQBQCdASoYABYAPuVepE2pJSMiMAwBIByJQBcGMZkIdrmUMn3qdTfJbJE9I+PWX+gAAP78RpkHKhk18oAw8cyuJz2CQJcxFeTXvKz1EzdPvEkaHdS48kpmgtOcKLjsI7LP5uCiLsm4a0BXsRrjle3Dx9yVa/9/hotVM8x0dfql3g96nU7AqjZt1F0C1Eq8LrCVZmVfg0hkmozAQ9NNAjZcARZ9VwCij1wjmVTPGhXIHQ5XeycpzQN5oGpI/J6xMgAAAA=="
  },
  {
    "id": "cafe-do-nthng-manali-lantern-fairy-lights-dusk",
    "category": "ambience-night",
    "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-lantern-fairy-lights-dusk-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-lantern-fairy-lights-dusk-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-lantern-fairy-lights-dusk-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "A glowing lantern and fairy lights over the terrace at dusk at Cafe DO NTHNG, with prayer flags and the Manali valley behind",
    "caption": "LANTERN LIGHT AT DUSK",
    "position": "center 35%",
    "featured": true,
    "blurDataURL": "data:image/webp;base64,UklGRjABAABXRUJQVlA4ICQBAACwBgCdASoYACQAPu1op0+ppiMiKqwBMB2JbACpJ9k6AC5Q2lLujyGHmYvKblVuM0ah9Gkca0nK3k6149+mAAD+w+JJ7H3psPzz2/kH4LeW2FxtYG2oCr6zGV6gkoUTyz3ifoot6Z0QSZI0SUIlItUZnZ+Qd32laOIXACqS71gvJFqSSa/N00yI4xPcRBx17Iu6Yir5O0SZ79y+5mJid5aW90rVC7Vv2hgJdu9aPJ/76c9mcAQzR3NWN/4Ye44HqLIB/RGLlfcb26Dr2TRqdQEZpMg4dhk7mpkqZ77YB1jKsmAdwI+ASU/Ua85aVixu99ffD0hJq8B+znrKEVzJvDTD9Er2cmdbvbQfJdyO0BfohiMPncASM7FJmt+xV84DuC2iAAAA"
  },
  {
    "id": "cafe-do-nthng-manali-candlelit-dinner-table-rose-petals",
    "category": "ambience-night",
    "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-candlelit-dinner-table-rose-petals-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-candlelit-dinner-table-rose-petals-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-candlelit-dinner-table-rose-petals-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-candlelit-dinner-table-rose-petals-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "A candlelit dinner table scattered with rose petals, set up at Cafe DO NTHNG in Manali",
    "caption": "A TABLE SET BY CANDLELIGHT",
    "position": "center 50%",
    "featured": true,
    "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaACdMoADgBNoyZAHp3NE3iI4AP7vSNFOjnKeh/zy1ZqmfbTR7zcyh5oaQ7VY/ppKwDIx4Mhs7kbnXWNR3YkhLTJWQKw9rl4Y94eBeZXnnIvBN8k86C9Emg5zf+RRNi2SagMQAAA="
  },
  {
    "id": "cafe-do-nthng-manali-candlelit-dinner-couple",
    "category": "ambience-night",
    "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-candlelit-dinner-couple-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-candlelit-dinner-couple-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-candlelit-dinner-couple-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-candlelit-dinner-couple-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "A couple smiling across a candlelit dinner table strewn with rose petals at Cafe DO NTHNG in Manali",
    "caption": "DINNER, UNHURRIED",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZACdMoADYZ4sp537hn/SAP6plAKPz/QmzGlbumWc7zpfbkXhs1VCuyIhPOKlH5kNV4Fc3MyUXBSWzcbJZPXuGodB5i+qvEqq9bPx8aDm1s5KNEwJZOuNMDxAmbvfDdncXUgHqL536oVaVOXL8Nu5HZ6Rp97Wb+jHisRIcAA="
  },
  {
    "id": "cafe-do-nthng-manali-night-terrace-fairy-lights",
    "category": "ambience-night",
    "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-night-terrace-fairy-lights-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-night-terrace-fairy-lights-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-night-terrace-fairy-lights-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/ambience-night/cafe-do-nthng-manali-night-terrace-fairy-lights-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "The Cafe DO NTHNG terrace at night in Manali, with fairy lights, a hanging lantern and guests seated around the tables",
    "caption": "THE TERRACE AFTER DARK",
    "position": "center 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAACQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYgCdMoADgPos/QaScTrqe84MisAA/ieObyDV3HhO2wyyk9bx4UDlP0dg8vJyB1nz25jfGzWgiB1ebU3JqAl/RHP8zJqN2v43LeS1aFOzodhcN77bk6TsDdI+Z01vcMKKV5Qd5Gz+V8Gyt6mZZYq1UesUDvMC6oqOabE0397GSgwarcL9m6PAAAA="
  },
  {
    "id": "cafe-do-nthng-manali-barista-at-work",
    "category": "team",
    "src": "/images/cafe-do-nthng/team/cafe-do-nthng-manali-barista-at-work-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/team/cafe-do-nthng-manali-barista-at-work-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/team/cafe-do-nthng-manali-barista-at-work-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "A barista in a green apron working at the counter at Cafe DO NTHNG in Manali",
    "caption": "BEHIND THE COUNTER",
    "position": "center 30%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRjIBAABXRUJQVlA4ICYBAACQBwCdASoYACQAPu1qqFAppiOiqqoBMB2JYgCsM4UIg8hVzkiR9cUcP2CFgLr7/xc4Nz3fXO4oG7AKEHfS2MKR9jKpncAA/tlaqDg7Z4B8kJP7GCqVJmUgzYk4jtPxyTB+XMEW8oBKAmCO26hOj5YHDnfkR0cZDI3YLnwgem60vdWjbLeklAOkyzG/fVrICI0qzmFbUmWJwgVczHs1MB6pIB13aQ2iosPEZMZqiztZ0eUgzN6cTboNftLjFLupH0v+Yv/S3U+6yyJT/AkA3Jae9kZ6ktyP/9iWvqYTZzSEshvhgcppQu4zrTsd1DYJjfZ+gBQY8sYpS3RliMlIKQaZ14XgNMAwNBKWmGAsEeQf54pjsR5PVK3xp1R2Vvg/CbST7gEAAAA="
  },
  {
    "id": "cafe-do-nthng-manali-team-neon-sign-entrance",
    "category": "team",
    "src": "/images/cafe-do-nthng/team/cafe-do-nthng-manali-team-neon-sign-entrance-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/team/cafe-do-nthng-manali-team-neon-sign-entrance-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/team/cafe-do-nthng-manali-team-neon-sign-entrance-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "The Cafe DO NTHNG team and guests posing together at the cafe's flower-arched entrance in Manali",
    "caption": "THE TEAM, AT THE DOOR",
    "position": "center 45%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRhQBAABXRUJQVlA4IAgBAABwBwCdASoYACQAPu1wqFAppqOiqrgMATAdiUAWcLa0oAKEYw0QQmclk7JJtCuBf2k5+MvIamj2G8JG1DNpuPK6yrhQAAD+7mPsTT0+0zSdo3H+YG9Vv4SmXEdHCSztdztK2e4Rcc6GNQlgcEkmpee0SIQ6ABNQcUMMvLEfXrbvE/WxtgTZkAFf02cBHi41jh7nUm2L4ORcglQRGRxjO/FYF4luS4j45WINy2ri6KZPFwpcSxkyqPJl1894MiciLVcscUbjycXqu9SkPfJdQ4DjgEsskMRy5KG+AZjxhvxGGtD3QgaS8GIDhC6GNn64PShUDv2CUOpLBaALTFS4mIKCT1p6AWoAAAA="
  },
  {
    "id": "cafe-do-nthng-manali-guests-terrace-prayer-flags",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/cafe-do-nthng-manali-guests-terrace-prayer-flags-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/cafe-do-nthng-manali-guests-terrace-prayer-flags-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/cafe-do-nthng-manali-guests-terrace-prayer-flags-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/guests/cafe-do-nthng-manali-guests-terrace-prayer-flags-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Guests chatting in wicker chairs on the Cafe DO NTHNG terrace in Manali, with prayer flags and apple trees behind",
    "caption": "A SLOW AFTERNOON ON THE TERRACE",
    "position": "center 45%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZgC06Bk4UVFC/q2hrIJW/yQA/niNSzM4DpWt9dKxDQIN6EmmyVARN7gybhNlrvZnPcYZmAeB33+8pL1BTISV8HNEi0qF5JfjnxATBwgcEbgRKgPl8llVaG9SLCWmu19bYZSfdtZKFkNOukj5JFo2aGpgyap0y5jHGV9ZLzyoAAAA"
  },
  {
    "id": "cafe-do-nthng-manali-guests-chatting-terrace-dusk",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/cafe-do-nthng-manali-guests-chatting-terrace-dusk-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/cafe-do-nthng-manali-guests-chatting-terrace-dusk-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/cafe-do-nthng-manali-guests-chatting-terrace-dusk-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "Two guests chatting at a terrace table at dusk at Cafe DO NTHNG in Manali, with an egg chair and mountains behind",
    "caption": "DUSK CONVERSATIONS",
    "position": "center 55%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRg4BAABXRUJQVlA4IAIBAADQBgCdASoYACQAPu1iq1CppSOjqrgMATAdiWMAxiVXAyn/Hoj1RqDmnYZ8hP3fkx0OvnGiYVZoL36pFsSm+IAA/vPuN7ZcA85WHnd5tbJwlpSYdZPyvZFYz0srCLr1SU24vNmJOl+Zyx+IX3qkQx358XQfnUN2SIIJ93LEXatwwP58B/INrD1fduIitpNJLJPGDIUTouuFKQhkJpsAzy4GbaK9QVZudpyRJ0Wc4Gso3cDYVGnV5cRRNvdW+67/ttdTO97APXcljGF6peQ6sPmHQ59SRB82x+LXXktv9b7AFiEE8gHRjdMqXL29YYMmZxHZaraEZf8mWCbk9U6ElEAAAAA="
  },
  {
    "id": "hogs-panorama-manali-guests-family-pointing-at-sign",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-family-pointing-at-sign-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-family-pointing-at-sign-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-family-pointing-at-sign-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-family-pointing-at-sign-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "A family pointing at the wooden HOGS sign and smiling, at HOGS Panorama in Manali",
    "caption": "FOUND US",
    "position": "center 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQBdkDgBXOnZlcPcENbUgHwAAAP7YNHfHwDup/k4wcc7z2QO9HgeFFm+Uyr/UgyXelthbfzdsLdXl413hANxv8OvmelULHt4hUEWGwhp41aCFQ7AJ+1cPiXT8j4MOinanhAlJSkZEWAmtEntvupUKNQqXck/xQyyDKgjOpGXoAA=="
  },
  {
    "id": "hogs-panorama-manali-guests-couple-at-hogs-sign",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-couple-at-hogs-sign-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-couple-at-hogs-sign-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-couple-at-hogs-sign-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-couple-at-hogs-sign-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "A couple smiling and gesturing at the wooden HOGS sign at HOGS Panorama in Manali",
    "caption": "ARRIVED",
    "position": "center 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JYgCdMoMul0jtuKGJPLoNMbh+ugAA/P9qB/52vFpEYAESG7B7sn6GGwQVS1O4z7Ndjse5vt1tzGrUe01N4PGBehjGkAREfrQbeeTPVyYXEq+FbQvrPhuzR3vuCVvBy1+5Kroqix+a4hHwqHpSywbVfozE4R+lYHERVnIto8xBANhs8AA="
  },
  {
    "id": "hogs-panorama-manali-guests-group-of-five-at-sign",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-group-of-five-at-sign-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-group-of-five-at-sign-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-group-of-five-at-sign-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-group-of-five-at-sign-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Five guests standing together beside the HOGS sign at HOGS Panorama in Manali",
    "caption": "FIVE FRIENDS, ONE SIGN",
    "position": "center 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwAwCdASoYABAAPu1mq04ppaQiMAgBMB2JagDG9B5l4xPKsNNbHQYAAP7rV5FzvV5pgs5H9q1dghfrpmGRM8LxwlFe3G8dRxtoChW9Csih0tp3kOuGr089bItd5F8JO9XquXd7ucOrxImfrF+G3rb+Hz6VoP1vw+hhRri4rvjN60Liwc2X1236GqO1DuL76IAAAA=="
  },
  {
    "id": "hogs-panorama-manali-guests-older-couple-at-sign",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-older-couple-at-sign-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-older-couple-at-sign-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-older-couple-at-sign-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-older-couple-at-sign-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "An older couple smiling beside the wooden HOGS sign at HOGS Panorama in Manali",
    "caption": "A WARM WELCOME",
    "position": "center 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACwAwCdASoYABAAPu1iqU2ppaQiMAgBMB2JQBdgBC1Vvo1Fa5XQCAD+6D7GO2/MxRZu5LQV0o03rXCMyEVp2YSIRS+HtTememwgS8/W7xwFGmDcvxWK84yUshEBtDqb5lg9s2+pQhGVXns8+6wKItze+px27O6wu2PjHcL8YdFThbeJsanAAA=="
  },
  {
    "id": "hogs-panorama-manali-guests-friends-pointing-at-sign",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-pointing-at-sign-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-pointing-at-sign-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-pointing-at-sign-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-pointing-at-sign-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Three friends pointing at the HOGS sign at HOGS Panorama in Manali",
    "caption": "THIS IS THE PLACE",
    "position": "center 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAAAQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JagCdMoABmJNiRuHVU3nnQAD+5dYwOvMlUGVrWLb69paLX1V/VpTPOwmHvi3JcwvcnMah8L+EI6m0PGkeck8ImJr911b0pFzAc/snhTAujxbjIVzXeMnwS41gW/XSz0BtXNTa2FykSbqEM+lJbrGP8dlrnE/dzT7SukQY1ww2566FWbqvXysw/k1PoPr7e72zpAAA"
  },
  {
    "id": "hogs-panorama-manali-guests-friends-laughing",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-laughing-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-laughing-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-laughing-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-laughing-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Four friends laughing together on the terrace at HOGS Panorama in Manali",
    "caption": "LAUGHTER, UNPLANNED",
    "position": "center 35%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaACdABn4rf4nDq5rLKDK7LYAAP6PESl8nffmAHe085HLUfSsGNDrRgCl7FjG0yx+orB6yCfUEXAcA7MVyLABVwlFGZ+T0WeKQeBAfSo5BsYNhkBSApAfHLOQ9u+aCTse30nm9QDqFb7q93DDWfSPxdiCItqpUSV0kHInJEIJluSxuJYem+edwAA="
  },
  {
    "id": "hogs-panorama-manali-guests-friends-valley-view",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-valley-view-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-valley-view-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-valley-view-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-valley-view-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Five friends posing on the terrace at HOGS in Manali with the valley and a green-roofed cottage behind them",
    "caption": "THE VALLEY BEHIND US",
    "position": "center 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYgCdMoADUwcL0CjGK0pi36n2AAD+eRlt27qgP+Eq67DQHQkSutZkjq8DrAX7ZnaSak0GannxgrE757Tv+2QHAKOj8IeXcxjSd1I4WB4Tj5PXDBJP192JKTPVNQioh742A6c+ZF20kn60BYtRepxGxfGoz8Ninyus8sclYB0PzWqyjRRhY5a55gjSmisAAAA="
  },
  {
    "id": "hogs-panorama-manali-guests-group-mountain-backdrop",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-group-mountain-backdrop-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-group-mountain-backdrop-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-group-mountain-backdrop-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-group-mountain-backdrop-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "A group of women posing together with the Himalayan mountains behind them at HOGS in Manali",
    "caption": "A GOOD DAY IN THE HILLS",
    "position": "center 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbAC06YwI7VSdH3z1V8s927sQAP7W6cCJoQSqjubzJcOSkXMx2eybmEvo+dbxN3CYFgRs616ExFPVGr7sy8q/qzWsXi5kvaZS+LoKIGEXB33kPgTxYvoZB2Jzxz9MlZxN9AnfLADFDm3dKX29tPKOjC+vD7o5NY/QF3IXflRrudQV/lC0wclnNAA="
  },
  {
    "id": "hogs-panorama-manali-guests-friends-snow-peaks",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-snow-peaks-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-snow-peaks-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-snow-peaks-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-friends-snow-peaks-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Five friends posing at HOGS in Manali with snow-capped peaks behind them",
    "caption": "SNOW PEAKS, GOOD COMPANY",
    "position": "center 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYgCdAYxsPAC8V/R4e+DmdgAA/rCsa/GYZ50nhwssde5d8WxC8Sg6J/H/ypf47jICJkXjZxer17jrT/jXrvMKxoGJ9eJbSyDY2efTGR2axL15aTeZg2Jv0yPHuSbuqS8CIaK16Rt2tLSpL9Qau/xr5CxBqn2xWSutu/xgVWhRFwVZDyrw6yf6oMOYk5Mtjij6NhLxCZLAkgAA"
  },
  {
    "id": "hogs-panorama-manali-guests-big-group-entrance",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-big-group-entrance-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-big-group-entrance-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-big-group-entrance-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-big-group-entrance-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "A large group of guests and staff gathered at the entrance of HOGS in Manali",
    "caption": "THE WHOLE GANG",
    "position": "center 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAACQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQBOgZYMMAYIjbKkJSk8MlJdW6AAA/et5CKgi+sERsnKFvAd4fFOWPrlbZQsPINmp4RQEBhKhKqrnHwHLX7a/O+LKknMtPxnCit2XBwTegQ7wwFm4jtUqe711Of3dsGjFSdM2rHbe0AkhD6HMdXTvflfodmS++USNrJ8wI+51LDgPYcbFffEnmTwX72OQAAA="
  },
  {
    "id": "hogs-panorama-manali-guests-terrace-group-photo",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-terrace-group-photo-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-terrace-group-photo-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/hogs-panorama-manali-guests-terrace-group-photo-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "Guests posing in a group on the Cafe DO NTHNG terrace in Manali, with mountains and prayer flags behind them",
    "caption": "ON THE TERRACE",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRhIBAABXRUJQVlA4IAYBAABwBgCdASoYACQAPu1oq0+ppaOiJW5hMB2JQBdmbky6RhQA17o/7Y4drQpp8QGnrAHb5ahBmIUag73+zgAA/vcKoxmQhNds+4KNJ1tjjWYsqiDXdSovaa4Xh0qkoXe384pE4VYts8AohI01ywxKMgYu6CKOxgAoD6K8FBXqxxPSnhrvg0VkXkQn6jxYhaMcInKOiQ7em9x+vho757YKNM7C/hEGV3si0MFUcI25SEuOYfdYKK4ZlcrBnQa1UXVQdRaY6k46KdJza8ORgHPu649tNPZKWpOzwF0h7daF/329GsQli02yIaaIRBJ3FEq8zpXF9vfjSFexLcRQyuRIkNz7wWa4wAAA"
  },
  {
    "id": "cafe-do-nthng-manali-guests-sharing-a-meal",
    "category": "guests",
    "src": "/images/cafe-do-nthng/guests/cafe-do-nthng-manali-guests-sharing-a-meal-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/guests/cafe-do-nthng-manali-guests-sharing-a-meal-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/guests/cafe-do-nthng-manali-guests-sharing-a-meal-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/guests/cafe-do-nthng-manali-guests-sharing-a-meal-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Guests sharing a meal around a long dining table beside tall windows at Cafe DO NTHNG in Manali, several smiling at the camera",
    "caption": "A LONG TABLE, A SLOW MEAL",
    "position": "45% 75%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZQDCgB8wRLDIdN1i27bV+T0YAP7h7zO3Hop/Q5JYQoxlBPVKAY3y4991fqqNtOoLnjWJoS7pFZZJH/YscHJ0LrLa27ZQQMJcXvvDtU/fir/DxQH3nrmrzqqz/p/sgqGJS1RpZu0O44mf1///F1o4IsHZXWu3LCksHBAJF3t02DgAHkQAAA=="
  },
  {
    "id": "cafe-do-nthng-manali-espresso-machine-black-and-white",
    "category": "behind-the-bar",
    "src": "/images/cafe-do-nthng/behind-the-bar/cafe-do-nthng-manali-espresso-machine-black-and-white-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/behind-the-bar/cafe-do-nthng-manali-espresso-machine-black-and-white-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/behind-the-bar/cafe-do-nthng-manali-espresso-machine-black-and-white-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/behind-the-bar/cafe-do-nthng-manali-espresso-machine-black-and-white-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Black and white close-up of the espresso machine with cups warming on top at Cafe DO NTHNG in Manali",
    "caption": "WHERE EVERY CUP BEGINS",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaQAD5aG4wCNV8JGdNN/VX6PAAP6tI/z8XL/iMM+tbsXQrqZ/PmleHL0DjPGyou/ZmK29cWyyCHrsQ1FmhdMXkNZNAVAQC6OH18iNb0Hc+/PxfG9SJBn5Ab1V4k5YlFozI48D1cx+PHm9cx3DNwj0MxM2UcRFrXyxNQAA"
  },
  {
    "id": "cafe-do-nthng-manali-barista-pulling-espresso-shot",
    "category": "behind-the-bar",
    "src": "/images/cafe-do-nthng/behind-the-bar/cafe-do-nthng-manali-barista-pulling-espresso-shot-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/behind-the-bar/cafe-do-nthng-manali-barista-pulling-espresso-shot-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/behind-the-bar/cafe-do-nthng-manali-barista-pulling-espresso-shot-1280.webp"
      }
    ],
    "width": 4480,
    "height": 6720,
    "alt": "Black and white photo of a barista in a HOGS apron preparing an espresso shot at the bar of Cafe DO NTHNG in Manali",
    "caption": "PULLED BY HAND",
    "position": "center 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRh4BAABXRUJQVlA4IBIBAABwBwCdASoYACQAPu1srFGppaQipWzJMB2JaQAIEEgBKzO9ty00b9ND/Eqq+2yeR3JlxVPTgSotQtdFXnsfaz+lwrJ/gAD9xpgghc15+WXBdmsKvPMatPe8IvbrWdL6QxXQDkc2cskHHEDcwsqlxb4Ah1oKzpd9LN+sVNUDu+2yx9fiv5ncQvLMdZciSUPYSINZr3YXAqcCAuJkmKtHFQGWa0MG1ZxsIxzVlTzeyT+pq8o/SrsCNHZliRwu7RbDHyz+JZ1l175Xl4goiYVIZFSFpYl3quBAweWcUyIlfPckbmGZzqCPPyGLCVSLcSuD/DQ5jFke8uapB71lsuwzTn40BxFUZ24jsDHwsm1QwxGgAAAA"
  },
  {
    "id": "cafe-do-nthng-manali-barista-at-espresso-machine-black-and-white",
    "category": "behind-the-bar",
    "src": "/images/cafe-do-nthng/behind-the-bar/cafe-do-nthng-manali-barista-at-espresso-machine-black-and-white-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/cafe-do-nthng/behind-the-bar/cafe-do-nthng-manali-barista-at-espresso-machine-black-and-white-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/cafe-do-nthng/behind-the-bar/cafe-do-nthng-manali-barista-at-espresso-machine-black-and-white-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/cafe-do-nthng/behind-the-bar/cafe-do-nthng-manali-barista-at-espresso-machine-black-and-white-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Black and white photo of a barista working the espresso machine at Cafe DO NTHNG in Manali",
    "caption": "A STEADY HAND",
    "position": "60% 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaQAD5hmL3lU9oL+9U5ax/zMAAP40RJlumfbmZFu1aiq6EYC2m4qj1DsZxmk+nU2/O1RomCdKNOPel7Zu+1RVqVK/+obZY59J95Vfl+DAfzKe44NAMHbKZLugYefaT9YyIgie1R7pVzD1RZARvD2vZFO7p14XGPl1mQAA"
  }
];
export const panoramaCoverList: PanoramaCoverImage[] = [
  {
    "id": "hogs-panorama-manali-cozy-bedroom-mountain-view",
    "category": "signature-view",
    "src": "/images/hogs-panorama/signature-view/hogs-panorama-manali-cozy-bedroom-mountain-view-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/signature-view/hogs-panorama-manali-cozy-bedroom-mountain-view-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/signature-view/hogs-panorama-manali-cozy-bedroom-mountain-view-1280.webp"
      },
      {
        "width": 1536,
        "src": "/images/hogs-panorama/signature-view/hogs-panorama-manali-cozy-bedroom-mountain-view-1536.webp"
      }
    ],
    "width": 1536,
    "height": 1024,
    "alt": "Cozy bedroom at HOGS Panorama, Manali, with warm lighting and floor-to-ceiling windows overlooking the valley",
    "caption": "A COZY ROOM WITH A VALLEY VIEW",
    "position": "50% 45%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAwBACdASoYABAAPu1iqU2ppaQiMAgBMB2JQBOgjsD/8JzT7PLYjrYhdwAA/I5Vb+FPTEGjqyHpPIKg9SaI3pJlMiMJu5xHhfRCQe8lEWFylXy1UMpb15kIFn7TvUoeatDf8vjPS8x+bPrt+bQU2gG3Lp2OdhjlmTGX+Is6g+1xfdMa4mbUTs/H1/UmPrvu81UhgecnN3xRBM263Uao5oETe2RaQ1AA"
  },
  {
    "id": "hogs-panorama-manali-snow-peaks-valley-village-perspective",
    "category": "views",
    "src": "/images/hogs-panorama/views/hogs-panorama-manali-snow-peaks-valley-village-perspective-1200.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/views/hogs-panorama-manali-snow-peaks-valley-village-perspective-640.webp"
      },
      {
        "width": 1200,
        "src": "/images/hogs-panorama/views/hogs-panorama-manali-snow-peaks-valley-village-perspective-1200.webp"
      }
    ],
    "width": 1200,
    "height": 1500,
    "alt": "Snow-capped peaks above a Himalayan village of colourful tin roofs in the valley, seen from HOGS Panorama in Manali",
    "caption": "A DIFFERENT KIND OF PERSPECTIVE",
    "position": "50% 55%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAADwBQCdASoYAB4APu1iqE2ppaOiMAgBMB2JQBOmY5ApA4m9JKTigwt6QP2Jzu8P23cXjVdbFcR4AADMj/kd9rLjBt2jrI8gRgAH0AUykbMPzRGV9GbDKmBwWon/1WMRn30fTRLAbW46pxLA9cDicLHvf/g2k4VfIZy/6SPK0yZfi6wKONmFz+YcVE4BYKjCBfZF0uNikEr2PQSd4gIyBRlm8mhV19CW9yiSnUusTs+dMxClPvdhefXp+iwh2JVIACKGl1uozOF5hvPwAAA="
  },
  {
    "id": "hogs-panorama-manali-sunrise-over-mountains",
    "category": "views",
    "src": "/images/hogs-panorama/views/hogs-panorama-manali-sunrise-over-mountains-720.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/views/hogs-panorama-manali-sunrise-over-mountains-640.webp"
      },
      {
        "width": 720,
        "src": "/images/hogs-panorama/views/hogs-panorama-manali-sunrise-over-mountains-720.webp"
      }
    ],
    "width": 720,
    "height": 1280,
    "alt": "Sunrise glowing through layered clouds over blue mountain ridges, with green trees and tin rooftops in the foreground, seen from HOGS Panorama in Manali",
    "caption": "MORNINGS, UNHURRIED",
    "position": "50% 40%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRhQBAABXRUJQVlA4IAgBAADwBgCdASoYACsAPu1irE+ppSQiMBVaqTAdiUAY1fB3BIyQ8HQA0fMikfMX9bBWM/gxNkYtNGuRC+UcInfyegQAAP5Zmw4tadQ9lmgZo5tDVGx7lqzOCHiq5D04CblrvNGDcyyhNqNrQftXyzCmxFyDpXoFftpgQe3h5vdVzqy5xpC4ohKNH6alLgUel3legZSBbRH3Z/PumKJ7sFfGJoMek03SYhe53Kf4giJXFzu/hYZTcCnY8AETxNOfmIpgAmKBlSZN9I5W70K/O5w17lrqfTCgBbO1xAUOlDXXXHljGFjZDNLYKcxFFMU7KmPocPoIU35UhlQGtqwvwzdiywmq3aUtkcQoAAA="
  },
  {
    "id": "hogs-panorama-manali-valley-view-room-bed-teal-armchairs-mountain-window",
    "category": "rooms/valley-view",
    "src": "/images/hogs-panorama/rooms/valley-view/hogs-panorama-manali-valley-view-room-bed-teal-armchairs-mountain-window-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/valley-view/hogs-panorama-manali-valley-view-room-bed-teal-armchairs-mountain-window-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/valley-view/hogs-panorama-manali-valley-view-room-bed-teal-armchairs-mountain-window-1280.webp"
      }
    ],
    "width": 1280,
    "height": 853,
    "alt": "Valley View room at HOGS Panorama in Manali: a king bed with a grey throw, two teal armchairs and a small table beside a window over misty mountains and green rooftops",
    "caption": "VALLEY VIEW ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYgCxDExDL3C0+LwfqzGaKoAA/pG+s7pW/mnT7fs3lS86CQv7u2NdbMFuFva/cqxL+Xs7vBYC6ClRJKZ5cC6/TZbJM1ZQ+WtWn28XLx+Gp8TWvRbLS9srDP4PE3b0yv0vXLVnsyjGwE2k1C5adtl+ZQlbQJTvgHmgAA=="
  },
  {
    "id": "hogs-panorama-manali-valley-view-room-grey-headboard-wall-lights-balcony",
    "category": "rooms/valley-view",
    "src": "/images/hogs-panorama/rooms/valley-view/hogs-panorama-manali-valley-view-room-grey-headboard-wall-lights-balcony-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/valley-view/hogs-panorama-manali-valley-view-room-grey-headboard-wall-lights-balcony-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/valley-view/hogs-panorama-manali-valley-view-room-grey-headboard-wall-lights-balcony-1280.webp"
      }
    ],
    "width": 1280,
    "height": 853,
    "alt": "Valley View room with a king bed, a grey padded headboard wall, two wall lights and a glass door to a balcony with chairs",
    "caption": "VALLEY VIEW ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQBdgAlG+Gw5g8l/GnER8IAD78HVx+0aIR6RN0aZ7x9HleMcBHQNhBricce/dn2fmpKXz9BuV1ql09PS3AZVgPUwRZhCuKtCermySFatr+ykwTXD10ciZrgauL3Lj/3bhRJ2z2g3as6RtZrMQeXWe/Zum6QQOZdkx3ACe4AA="
  },
  {
    "id": "hogs-panorama-manali-valley-view-room-tv-armchairs-valley-window",
    "category": "rooms/valley-view",
    "src": "/images/hogs-panorama/rooms/valley-view/hogs-panorama-manali-valley-view-room-tv-armchairs-valley-window-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/valley-view/hogs-panorama-manali-valley-view-room-tv-armchairs-valley-window-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/valley-view/hogs-panorama-manali-valley-view-room-tv-armchairs-valley-window-1280.webp"
      }
    ],
    "width": 1280,
    "height": 853,
    "alt": "Valley View room with a television unit, two teal armchairs and a large window onto the misty valley, with the foot of the bed in the foreground",
    "caption": "VALLEY VIEW ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZQAGyAEsPmbcecbjq7jBjQAA/onEYU5555bAolnuQhcyqnBWAbgJoVYFiTaPE5U7BBYq3s9ZK3sH1Lms9uGwH7LzlRlcvQKe1ZrK48yoRN+bUTjvStS9n5DmNIQaf6Pwi8MhUfPnwPFvxVltqR/YF4bKAAAA"
  },
  {
    "id": "hogs-panorama-manali-valley-view-room-wardrobe-tv-bed",
    "category": "rooms/valley-view",
    "src": "/images/hogs-panorama/rooms/valley-view/hogs-panorama-manali-valley-view-room-wardrobe-tv-bed-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/valley-view/hogs-panorama-manali-valley-view-room-wardrobe-tv-bed-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/valley-view/hogs-panorama-manali-valley-view-room-wardrobe-tv-bed-1280.webp"
      }
    ],
    "width": 1280,
    "height": 853,
    "alt": "Valley View room with a wooden wardrobe, a television unit and a king bed, and a glass balcony door at the back",
    "caption": "VALLEY VIEW ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACdIJPC9ufbgoJMxytz9rOL8AD+icQQAhE/qgEKiP1LM5qINr/UPy1AaVus3hD5M+tf2m9K6+T4Jar/RmPQHKGSE4ZadCWY36T1ZxUyECkLwyqFOuH5627Widw5c1X6EoJ3W+2q2GyTMXDH4NCYTqWcYv6nW+4e6CyGeJ9R2su9agAAAA=="
  },
  {
    "id": "hogs-panorama-manali-signature-view-room-floor-to-ceiling-window-balcony-mountains",
    "category": "rooms/signature-view",
    "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-floor-to-ceiling-window-balcony-mountains-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-floor-to-ceiling-window-balcony-mountains-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-floor-to-ceiling-window-balcony-mountains-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-floor-to-ceiling-window-balcony-mountains-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Signature View room with floor-to-ceiling windows and a balcony door onto misty mountains, two teal armchairs, a television unit and a king bed",
    "caption": "SIGNATURE VIEW ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQBOg7wAR4ks1UtyPtz6PAAD+MWZ05zDCuawkA6wcxQmscb8Icv2oNPnyV39H0yOzNe24k6/5/c5UOWMQw9pspVUDXYT+3zvTazCTP/32CTwrSzOalo0qOYhmH/EujEaWvfifpB4I+By6UW0qjOMbGblYOT4a052JAAAA"
  },
  {
    "id": "hogs-panorama-manali-signature-view-room-bed-wall-tv-valley-window",
    "category": "rooms/signature-view",
    "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-bed-wall-tv-valley-window-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-bed-wall-tv-valley-window-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-bed-wall-tv-valley-window-1280.webp"
      }
    ],
    "width": 1280,
    "height": 853,
    "alt": "Signature View room with a king bed and striped cushions, a wall-mounted television on a wood panel and a large window over the mountain valley",
    "caption": "SIGNATURE VIEW ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JQBadZYJ0AZYqmIe2vLS5LzGnOgAA/oLY2VfqbNpxXOthGxY1J9A5F4WAdGnXYlD/qDidg04OfWQs/9lnmzKy5mp5ICO/4B9Z8ks0NzzCWwrCC+/91OKdc9HvUko5ka6UPcrCY+6rwm5NS0aZzqaWyD8LRNFUdc1h8HBttU9rAFKSvhYevNO+nOgAAA=="
  },
  {
    "id": "hogs-panorama-manali-signature-view-room-bed-wall-lights-tray-ceiling",
    "category": "rooms/signature-view",
    "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-bed-wall-lights-tray-ceiling-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-bed-wall-lights-tray-ceiling-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-bed-wall-lights-tray-ceiling-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-bed-wall-lights-tray-ceiling-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Signature View room with a king bed, wall lights and a layered tray ceiling, with two teal armchairs by the window",
    "caption": "SIGNATURE VIEW ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAACQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JagCdMoR3ACZPqfLrC7ysKJvrSAAA/t2o2rt3+c4TrqXhtZ7TGJU+qzxqM2tbDoT0SrGoznyealZ3dE+OvtkYYtWBLEDLH7OBIa7834xe0+tr/U/CniAslNHlkCQQ1/aVdFGN7/blsLPyxmqbzODF9Z3eKdt6w60MeF2oevnzrwqXXpsPrIKR8DSQQp0AAAA="
  },
  {
    "id": "hogs-panorama-manali-signature-view-room-teal-armchairs-desk-mountain-window",
    "category": "rooms/signature-view",
    "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-teal-armchairs-desk-mountain-window-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-teal-armchairs-desk-mountain-window-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/signature-view/hogs-panorama-manali-signature-view-room-teal-armchairs-desk-mountain-window-1280.webp"
      }
    ],
    "width": 1280,
    "height": 853,
    "alt": "Signature View room with two teal armchairs and a small table beside a large mountain-view window, a desk and a wooden wardrobe, and the foot of the bed in the foreground",
    "caption": "SIGNATURE VIEW ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADwAwCdASoYABAAPu1iqk4ppaQiMAgBMB2JaACdABRiZ7+UbD/vyVfgAMwQ1/hyFO9b2EIUjj/OhdrRqzn21bnEpvLYZjxwYbhhuWCawTKr53bAhHXkRYbr3a2eQ816XLBfozEIxp1Icfxz8b6VN3eTjjbzZwTIU26sxCzeaU5cvy4cZqXaO4RzwAA="
  },
  {
    "id": "hogs-panorama-manali-premium-room-timber-ceiling-bed-window-armchairs",
    "category": "rooms/premium",
    "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-timber-ceiling-bed-window-armchairs-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-timber-ceiling-bed-window-armchairs-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-timber-ceiling-bed-window-armchairs-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-timber-ceiling-bed-window-armchairs-1920.webp"
      }
    ],
    "width": 6595,
    "height": 4397,
    "alt": "Premium room under a pitched timber ceiling with a king bed and grey throw, wall lights, two teal armchairs and a large window over the town and mountains",
    "caption": "PREMIUM ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZgCdMoACCyG2dAlOtLmctwAA/sGhghHZWwSmoea858DGwPyJQfZV3RwDe+Bg5F2JNECvhgDNaGIVPKMHgEUt8s1DWP666OhEh+3Ya2i1WB3IhMad/e5q+eRz8vV6Ca5jk4jzwr28Cgrr36d7iNhf5412/KifxbST57ohjNJ9dRbBaneK4qG2REqH4fYoAPqUeuGeAAA="
  },
  {
    "id": "hogs-panorama-manali-premium-room-timber-ceiling-bed-wall-lights",
    "category": "rooms/premium",
    "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-timber-ceiling-bed-wall-lights-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-timber-ceiling-bed-wall-lights-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-timber-ceiling-bed-wall-lights-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-timber-ceiling-bed-wall-lights-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Premium room under a pitched timber ceiling with a curtained gable window, a king bed with a padded headboard, wall lights and a wooden bedside table",
    "caption": "PREMIUM ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAADQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZgCdMoAlxBlnOIFN+i6N2N/FNCByAAD2tlbH7kX+8hxcj5cs3rqx2LNYgxwARpPHJUGdcwyUrLowbXKsHf7EIwxtHIIIPSYZuszRq0Q+85BjuvTeiqNxC/DaTdK1GGIwunzWu7TsviB4YVW8ijGFu2AxukmttHvqUdaUTZgez9NcbnyjY7Mq7Kk8+JlAAAA="
  },
  {
    "id": "hogs-panorama-manali-premium-room-balcony-door-valley-view-armchairs",
    "category": "rooms/premium",
    "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-balcony-door-valley-view-armchairs-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-balcony-door-valley-view-armchairs-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-balcony-door-valley-view-armchairs-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-balcony-door-valley-view-armchairs-1920.webp"
      }
    ],
    "width": 6720,
    "height": 4480,
    "alt": "Premium room under a timber ceiling with a glass balcony door and a large window over the valley, a television unit and teal armchairs",
    "caption": "PREMIUM ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JaACdMoMYAB5j4MQF4cxcAP2QJbvK2rSTryd0Vdny119Bs+nvKt8sMQYTp22EpFuVh8O5UFFKbVphdACsjhu+nRGS21VKr6huuLzg2PdeuQ0y9Sn8HUZdcMXDVcvhKhWfdeULirH5zEiFxz2DMYXuHk4n4DQjWy32YtUI4SXndnjjL0zkysEy1pdMTs9TvfGIHIAA"
  },
  {
    "id": "hogs-panorama-manali-premium-room-tv-armchairs-valley-window",
    "category": "rooms/premium",
    "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-tv-armchairs-valley-window-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-tv-armchairs-valley-window-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/premium/hogs-panorama-manali-premium-room-tv-armchairs-valley-window-1280.webp"
      }
    ],
    "width": 1280,
    "height": 853,
    "alt": "Premium room under a timber ceiling with a television unit, two teal armchairs by a large window, and a mirror and door at the back",
    "caption": "PREMIUM ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQBOj+AhwBNsKoKtW989xZK2LQAD+3OFKoTPTEmcpgmRT4UwVVDmLpGLAU6cxc4dKkJt9NMre5r6l2A3YYMAmRks6SQg3fSc3Fn6Ymm8GvGG/vVHrzsw3GIFJ1xvNmiRBK2UL2O9UjhMu5l7b00FuHR2Vo6pRuYeDwGOg29Kqm7OKIr25ffjYK2RDqAAA"
  },
  {
    "id": "hogs-panorama-manali-jacuzzi-lit-tub-mountain-view-window",
    "category": "rooms/jacuzzi-room",
    "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-lit-tub-mountain-view-window-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-lit-tub-mountain-view-window-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-lit-tub-mountain-view-window-1280.webp"
      },
      {
        "width": 1537,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-lit-tub-mountain-view-window-1537.webp"
      }
    ],
    "width": 1537,
    "height": 1023,
    "alt": "In-room jacuzzi with coloured lights beside a large glass door with a Himalayan mountain view at HOGS Panorama, Manali",
    "caption": "THE JACUZZI, FACING THE MOUNTAINS",
    "position": "center 62%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAACQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaACdMoADK1PlwRznBd5EMO/IQaAA/vDevpy30tMNT7zAiKNv8aBx3kKj8anUMfVeZnO73kuRUIvgaS/Btqt0L3xjzoG3dRwXWUTv1VH7kbd7j/+zqfLq2NgthMPht7XV4gR6szAnw+belmItXBTcEWcyh1XnuZpbrHQ7GVhVe73QQ5V9oo3PfO8vl1x7AAAAAA=="
  },
  {
    "id": "hogs-panorama-manali-jacuzzi-bubbling-lit-tub-bed-mountain-door",
    "category": "rooms/jacuzzi-room",
    "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-bubbling-lit-tub-bed-mountain-door-1023.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-bubbling-lit-tub-bed-mountain-door-640.webp"
      },
      {
        "width": 1023,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-bubbling-lit-tub-bed-mountain-door-1023.webp"
      }
    ],
    "width": 1023,
    "height": 1537,
    "alt": "Close view of the lit, bubbling in-room jacuzzi with the bed, armchairs and a mountain-view glass door behind it, Jacuzzi Room at HOGS Panorama, Manali",
    "caption": "A SOAK AT DUSK",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRjABAABXRUJQVlA4ICQBAABQBwCdASoYACQAPu1irU+ppSQiKrgMATAdiWwAnTKEe1kej/wFucmLDBwTk++1qV9lyMDVhgxZ+WSBgedq3xQaNZUAAP7vQxJzO3CKkQ4xh8QHTcLjLXdGFb/R1/GbyywGZrwXM+/qKzfZ69d19T40PnLVRkQXqvllNe3CjFHu2qd0S1INpnO3bkSqMa9bPdpn9soQqhgPu+nVGkM1ic8KcXwnc9WS+Ciea09RpGcpHNpjy8sp9flVtdr+DLhRfLmrBIsw0Vru0tAv3xYEdqdWPIBAkyrWXmrrWS6i4tPOUNqhto8oKmD16fv/6xm3CyzJGd0DQblNQg3143WtSa3GQz7m4bADNGp4MLGWy6uyinyWhJ1IoiY8rpYOJ30qK2UQAAAA"
  },
  {
    "id": "hogs-panorama-manali-jacuzzi-king-bed-gable-window-mountains",
    "category": "rooms/jacuzzi-room",
    "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-king-bed-gable-window-mountains-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-king-bed-gable-window-mountains-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-king-bed-gable-window-mountains-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-king-bed-gable-window-mountains-1920.webp"
      }
    ],
    "width": 2000,
    "height": 1333,
    "alt": "In-room jacuzzi in the foreground with a king bed and a gable glass door framing the evening mountains, under a timber ceiling at HOGS Panorama, Manali",
    "caption": "JACUZZI ROOM",
    "position": "center 55%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoABZ9/+MY3FVdxgAP7AWYtIBk5E94ir5jfuF+hmPoCp3b0GiQF5MU/ssXI/RM5LzF3YX1K0RV0cI3mxKww+JvB6bzivYSu5UlHHP29rAAXqOqJanLUT/Z4qu0Rjn3+9CZ5rxS61t4nES8C/eVDjpYdExb+dOlgp/kXdSAAA"
  },
  {
    "id": "hogs-panorama-manali-jacuzzi-tub-timber-ceiling-mountain-view",
    "category": "rooms/jacuzzi-room",
    "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-tub-timber-ceiling-mountain-view-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-tub-timber-ceiling-mountain-view-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-tub-timber-ceiling-mountain-view-1280.webp"
      }
    ],
    "width": 2000,
    "height": 3000,
    "alt": "White in-room jacuzzi under a pitched timber ceiling with a glass door and evening mountain view beyond, Jacuzzi Room at HOGS Panorama, Manali",
    "caption": "JACUZZI ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRiABAABXRUJQVlA4IBQBAABQBwCdASoYACQAPulmpU2pJiMiMBqtUSAdCWoAtSFBVL4qodBG4GlqzQhzdP9zx+OUM47U3W3TpDaZJb3QQOQ+o8YAAP7vV0tdF3CAY5IBfOkJQtUwVRtLjYEHeC0B+xaFkIZJd00h6JWWwRgVZfU+SaioDTulD6KtuUZk3RMlBSNUKaqiC8juZ/RzVxKN0E3ewWaAVh8GJHDCP+GdFMbMqmWN5GmZAnCIu5FkJvuKg3XfZxbTYktwnmqP8kekn6jOmOVZICGt+T4CqhoKOQOLkYFpwuaKqEmkO0JB0neeSuMRJb9xCCmHiXkJBy8ZbH0fT2LQqegxc5vPXDO1BpHWK2YR6thtdETRvUPmFjwSBMSYAAA="
  },
  {
    "id": "hogs-panorama-manali-jacuzzi-beside-king-bed-wood-panelled-wall",
    "category": "rooms/jacuzzi-room",
    "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-beside-king-bed-wood-panelled-wall-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-beside-king-bed-wood-panelled-wall-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-beside-king-bed-wood-panelled-wall-1280.webp"
      },
      {
        "width": 1537,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-beside-king-bed-wood-panelled-wall-1537.webp"
      }
    ],
    "width": 1537,
    "height": 1023,
    "alt": "Jacuzzi Room at HOGS Panorama with the in-room jacuzzi beside a king bed, a wood-panelled wall, an oval mirror and a timber ceiling",
    "caption": "JACUZZI ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACdIExgwBiEOpKhu9xsLRhFAdnUAP6xC6og3YWWuWidu9LAFyPynx68hR+s778Uylq40JVVxOn8S6krcTLdCMxVUIIEJOlpDCQ3KtMVdlLm7sA6nIy8CS4zpOKIo995d38CSJ3xBqnKuTysT484v+/4x9hS3prWfvvof8wa0FMI4AXM3/nkhFZ98ZcgGrc8XNXJ4qgAAA=="
  },
  {
    "id": "hogs-panorama-manali-jacuzzi-and-king-bed-striped-throw-oval-mirror",
    "category": "rooms/jacuzzi-room",
    "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-and-king-bed-striped-throw-oval-mirror-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-and-king-bed-striped-throw-oval-mirror-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-and-king-bed-striped-throw-oval-mirror-1280.webp"
      },
      {
        "width": 1537,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-and-king-bed-striped-throw-oval-mirror-1537.webp"
      }
    ],
    "width": 1537,
    "height": 1023,
    "alt": "In-room jacuzzi and a king bed with a striped throw, a wood-panelled wall with the HOGS sign and an oval mirror, Jacuzzi Room at HOGS Panorama, Manali",
    "caption": "JACUZZI ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAADQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JagCdMoRwAdDQ+smEQ3BYYMN9pyN7LAD+siqdZh65wVjXIeFAUV2X3kxjMbH2+jaSADSLYxAl7WDpRv/dIskGBSc5otqFxi47rg+TJdmt9gXrFBm3stpHwDgClWXrLVKFONvyXF/pQwH8em0cNXDXQqtc5IzRnkyTxJlTSf8deq7NjeWLcYUnfBrB2OBSMWSXhIErAm8TDXZpogA="
  },
  {
    "id": "hogs-panorama-manali-jacuzzi-room-bed-tub-timber-wall",
    "category": "rooms/jacuzzi-room",
    "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-bed-tub-timber-wall-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-bed-tub-timber-wall-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-bed-tub-timber-wall-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-bed-tub-timber-wall-1920.webp"
      }
    ],
    "width": 2000,
    "height": 1333,
    "alt": "Jacuzzi Room at HOGS Panorama with the in-room jacuzzi, a king bed on a wooden frame, a wood-panelled wall and an oval mirror",
    "caption": "JACUZZI ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAACQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaACdMoADEJdnLiF8ymN4LbihCxgA/I5SaG5OPj/r8dPN73V4E5AfYnzcZLJfWF0/aiBu66y1bkA+jTNAhJ4fxC+ze3G15/YPfRjWQxCcLSlipbO3XQbxq44uTLx5UvWlfZWAO553TH0tOxXzvC07YcRZEI7k5X1CbwQnpzNCVDkBmBnWhrnFg8+QvCQQAAA="
  },
  {
    "id": "hogs-panorama-manali-jacuzzi-room-foot-of-bed-tub-mirror",
    "category": "rooms/jacuzzi-room",
    "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-foot-of-bed-tub-mirror-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-foot-of-bed-tub-mirror-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-foot-of-bed-tub-mirror-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-foot-of-bed-tub-mirror-1920.webp"
      }
    ],
    "width": 2000,
    "height": 1333,
    "alt": "Foot of the king bed with the in-room jacuzzi, an oval mirror and a wood-panelled wall behind, Jacuzzi Room at HOGS Panorama, Manali",
    "caption": "JACUZZI ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADQAwCdASoYABAAPu1iqU2ppaQiMAgBMB2JQBOgAxpInPUZfAl/86AA+LW/drqr3aeajMdVg+m527zkE1UJ3fPolvBPIMvABL9DQ1rS+cK2UM0bVL6S6Getk70tBx0l1NAXxodU/vR8clFGdfi8861dya0JJaaO2mjeiUd3xQVy39AvvTpimzcj+baqUaXrAEfr+OAAAAA="
  },
  {
    "id": "hogs-panorama-manali-jacuzzi-room-tv-wall-green-armchairs-tub",
    "category": "rooms/jacuzzi-room",
    "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-tv-wall-green-armchairs-tub-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-tv-wall-green-armchairs-tub-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-tv-wall-green-armchairs-tub-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-tv-wall-green-armchairs-tub-1920.webp"
      }
    ],
    "width": 2000,
    "height": 1333,
    "alt": "Jacuzzi Room with a wall-mounted television on wood panelling, two green armchairs by the balcony door and the jacuzzi at the edge of the frame",
    "caption": "JACUZZI ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZgCdMoACakgZnhjNLKFjK9+AAP7CQU5fAIGq0W2Sq3qOWI1nmsjhPNI9PRaS6yJqB2lcMP4NT8l0/cfwKV+4ogRc9uTfgn3k3Yd7J+RceQi4K9+6Q1IL0PYE6cJugbWeW0eczlJxIteXHh1RMFoIshYQgAAA"
  },
  {
    "id": "hogs-panorama-manali-jacuzzi-room-king-bed-tv-armchairs-valley-door",
    "category": "rooms/jacuzzi-room",
    "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-king-bed-tv-armchairs-valley-door-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-king-bed-tv-armchairs-valley-door-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-king-bed-tv-armchairs-valley-door-1280.webp"
      },
      {
        "width": 1536,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-king-bed-tv-armchairs-valley-door-1536.webp"
      }
    ],
    "width": 1536,
    "height": 1024,
    "alt": "King bed with a striped throw, a television on a wooden unit, green armchairs and a balcony glass door with a view over the hills, Jacuzzi Room at HOGS Panorama",
    "caption": "JACUZZI ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAADQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoRwIsAKMAQo/I0Ohigj+Dd0AAD+6iydnQIo8YamZtDTJxs1nyxffV6wTINsytg0LGY/T3Q8RnWDf4xQ3Apd/SJjXtdDWs1xnrnSNeIRQYPNM8m6xKOq05FUprst9sa5JadQTNLAG97D/csUuKupX1fOzKrp8oD5R5AMKRF55qIOcd2oe2WYDFbBP52P6w+yunHesfZzKEn0YE0EITkdmjng9qWkJfM1LqnMXVFAAAA="
  },
  {
    "id": "hogs-panorama-manali-jacuzzi-room-king-bed-balcony-door-mountains",
    "category": "rooms/jacuzzi-room",
    "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-king-bed-balcony-door-mountains-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-king-bed-balcony-door-mountains-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-king-bed-balcony-door-mountains-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-king-bed-balcony-door-mountains-1920.webp"
      }
    ],
    "width": 2000,
    "height": 1333,
    "alt": "King bed on a timber frame beside a glass balcony door with evening mountain views, Jacuzzi Room under a pitched timber ceiling at HOGS Panorama",
    "caption": "JACUZZI ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACwBACdASoYABAAPu1iqU2ppaQiMAgBMB2JbACdMoR3JoA1gBL5yt1nS2LNQ1kAAP7d+nQ19O3x8Kom5BfFa+TKHCCx381faLjiPe9G2ED3/prNOHmOSIOUI7xD1lcvJjk/95MrDPC7u9CbJG9j/xbR+bnHgg2UOCQdByR55WVMOEorhz6EIUJG2+Y7nRO094XMAGGqOuGQVh/z4Zvk3f8m7erQH/x7Wjhjer6wAAA="
  },
  {
    "id": "hogs-panorama-manali-jacuzzi-room-green-armchairs-balcony-door-dusk",
    "category": "rooms/jacuzzi-room",
    "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-green-armchairs-balcony-door-dusk-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-green-armchairs-balcony-door-dusk-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-green-armchairs-balcony-door-dusk-1280.webp"
      },
      {
        "width": 1920,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-green-armchairs-balcony-door-dusk-1920.webp"
      }
    ],
    "width": 2000,
    "height": 1333,
    "alt": "Two green armchairs and a small table by the glass balcony door, with the mountains at dusk beyond, Jacuzzi Room at HOGS Panorama, Manali",
    "caption": "THE VIEW FROM THE ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbAC7MoGv/gLOrDFXD57Ugb44AAD+0cmKiWg0zPj6DqiofvqqRpp9hXt2WavUwgobIK/ESgFGXTDNYTiuHKluReoNoFMKVEXkHOXTIh8IsgCZaRtlbq0XU+8j2YxnoptWH5za1Emc4FYnxW7NINx2RCz94LFyDzmkRG56LoHU14Rem164NSCegUcmxWYwtAA="
  },
  {
    "id": "hogs-panorama-manali-jacuzzi-room-armchair-balcony-door-himalayas",
    "category": "rooms/jacuzzi-room",
    "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-armchair-balcony-door-himalayas-1280.webp",
    "srcSet": [
      {
        "width": 640,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-armchair-balcony-door-himalayas-640.webp"
      },
      {
        "width": 1280,
        "src": "/images/hogs-panorama/rooms/jacuzzi-room/hogs-panorama-manali-jacuzzi-room-armchair-balcony-door-himalayas-1280.webp"
      }
    ],
    "width": 2000,
    "height": 3000,
    "alt": "Green armchair and a small table by the balcony glass door looking out to the Himalayas at dusk, under a timber-lined ceiling at HOGS Panorama",
    "caption": "THE VIEW FROM THE ROOM",
    "position": "center 50%",
    "featured": false,
    "blurDataURL": "data:image/webp;base64,UklGRiYBAABXRUJQVlA4IBoBAAAwBwCdASoYACQAPu1qrU+ppiQiKqoBMB2JbACdMs8tRsrxupD6JHIYrxhrPSPRs+wLHPA4+8ZaxyxaLcx7Xo3VKYAA/uw2O455SEfgaoNykznPwOOWDZfMl6yisa+V8Ly6f6ymek9WGfGmwHw4ZE1OpzYMf9ixUeo8kyjzo0qOcUQsMyl121l5BSpL07Tjes4m/WMeuVvcp0IcSDVEKoXG1PrBYkFmPfDYshAFnuWMrS8PEvfV9dx/EAb74BYFdd9Qi6dukVF+DFTn8uzd9GCpyeovtz+hpSME8+2wJiI+fJV3FH/DmVBdLGb/Ti4E+3HvTgI27oLiG8iPykBMQ22Cupg0TrR4LFNceYPsOWjSPjheuYIcQqZKAAA="
  }
];
