// HOGS Panorama photography. The data itself is generated (lib/gallery.generated.ts, from scripts/gallery-manifest.json by
// `npm run images`) so file names, dimensions, alt text and blur placeholders can never drift from what is on disk.
import { galleryImages, type GalleryCategory, type GalleryImage } from './gallery.generated';
import { panoramaCoverList, panoramaOgImage } from './cafeImages.generated';
export { panoramaOgImage };
export type { GalleryCategory, GalleryImage, GalleryOrientation } from './gallery.generated';

/** Cover photo for HOGS Panorama (stays slider + /stays/panorama hero), generated by `npm run images:cafe`. */
export const panoramaCoverImage = panoramaCoverList[0];
/** Extra HOGS Panorama view photos (public/images/hogs-panorama/views), used by the home postcards. */
export function findPanoramaView(id: string) {
  const match = panoramaCoverList.find(image => image.id === id);
  if (!match) throw new Error(`gallery: no panorama view "${id}". Check scripts/cafe-images.json and run npm run images:cafe.`);
  return match;
}
export const gallery: readonly GalleryImage[] = galleryImages;

export const galleryFilters = [
  { id: 'all', label: 'All' },
  { id: 'common-area', label: 'Common Area' },
  { id: 'signature-view', label: 'Signature View' },
  { id: 'valley-view', label: 'Valley View' },
  { id: 'outdoor', label: 'Outdoor' },
  { id: 'jacuzzi-room', label: 'Jacuzzi Room' },
] as const;
export type GalleryFilter = (typeof galleryFilters)[number]['id'];

export const galleryByCategory = (category: GalleryCategory) => gallery.filter(image => image.category === category);
export const galleryFeatured = gallery.filter(image => image.featured);

/** Look a photo up by its descriptive subject (the file name without the "-hogs-panorama-manali-nn" suffix). Throws at import
 *  time if it does not exist, so a typo or a removed photo fails the build instead of rendering a broken image. */
export function findImage(subject: string): GalleryImage {
  const image = gallery.find(item => item.id === subject || item.id.startsWith(`${subject}-hogs-panorama-manali-`));
  if (!image) throw new Error(`gallery: no image with subject "${subject}". Check scripts/gallery-manifest.json and run \`npm run images\`.`);
  return image;
}
