// AUTO-GENERATED by scripts/package-images.mjs from scripts/package-images.json. Do not edit by hand; run `npm run package-images`.
export type PackageImageCredit = { author: string; license: string; licenseUrl: string; source: string };
export type PackageImageKey = 'hadimba' | 'oldManali' | 'mallRoad' | 'solang' | 'atal' | 'atalGreen' | 'sissu' | 'peaks' | 'paraglider' | 'cafe' | 'sajla' | 'sethan' | 'hamta' | 'naggarCourtyard' | 'naggarBalcony' | 'roerich' | 'jana' | 'beas' | 'vashishtTemple' | 'hotSpring' | 'manuTemple' | 'dhungri' | 'sissuFalls';
export type PackageImageData = { src: string; alt: string; caption: string; position: string; width: number; height: number; blur: string; credit?: PackageImageCredit };
export const packageImages: Record<PackageImageKey, PackageImageData> = {
  "hadimba": {
    "src": "/images/manali/Hadimba-Temple-1.png",
    "alt": "Hadimba Devi Temple's tiered wooden roofs rising among tall deodar trees under a blue sky",
    "caption": "HADIMBA DEVI TEMPLE, AMONG THE DEODARS",
    "position": "center 55%",
    "width": 1080,
    "height": 1080,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwX/xAAhEAABAwQBBQAAAAAAAAAAAAABAgMRAAQSIQUiMUJxkf/EABUBAQEAAAAAAAAAAAAAAAAAAAED/8QAGREBAAIDAAAAAAAAAAAAAAAAAQACESEx/9oADAMBAAIRAxEAPwBG+RAYQgkHKjcu24GCumQdDualMOvMozVbOKkwFTr1EH7RquUuOEEKanxBy2aW66zJlDs//9k="
  },
  "oldManali": {
    "src": "/images/manali/Old-Manali.png",
    "alt": "A weathered wooden mountain house with a stacked slate roof and a painted doorway, set against a forested hillside",
    "caption": "SLATE ROOFS & WOODEN BALCONIES",
    "position": "center 50%",
    "width": 1080,
    "height": 1080,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAID/8QAIBAAAwACAgEFAAAAAAAAAAAAAQIDAAQREgUhMVGCwf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAGREBAAIDAAAAAAAAAAAAAAAAAQACEjFB/9oADAMBAAIRAxEAPwCq+RkykLVTz6A9hgdi/eitOkz9wMCdNbozwJLKCxVvzM6aTpqLUIin3C88t8ZGQ7gUOT//2Q=="
  },
  "mallRoad": {
    "src": "/images/manali/Mall-Road.png",
    "alt": "Mall Road in central Manali at dusk, with a bronze statue, rooftop cafes and shop signs under a blue sky",
    "caption": "MALL ROAD, AT DUSK",
    "position": "center 45%",
    "width": 1080,
    "height": 1080,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIDBP/EACEQAAIBAwMFAAAAAAAAAAAAAAECAwAREgUhsQQUQUJx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAXEQADAQAAAAAAAAAAAAAAAAAAARES/9oADAMBAAIRAxEAPwAR65kwXqIlUn2Qnipya28gDYLIg2xGx+is/avAoaXJ7b5A3tSRiWRg0cLE+CwtzVNMER//2Q=="
  },
  "solang": {
    "src": "/images/manali/Solang-Valley.png",
    "alt": "Paragliders over a wide snow-covered valley at Solang, with pine slopes and white peaks behind",
    "caption": "SOLANG VALLEY IN SNOW",
    "position": "center 55%",
    "width": 1080,
    "height": 1080,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQIE/8QAIBAAAgEEAQUAAAAAAAAAAAAAAQIDAAQREiEFEzJRgf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFxEBAAMAAAAAAAAAAAAAAAAAAAERIf/aAAwDAQACEQMRAD8Aahu7KUqpmMcjDOkilTWsLbqM91ePfFGXJdpYYhbLMr+ZYcJ9xUz9OUltIEdcZC7kDNVmxx//2Q=="
  },
  "atal": {
    "src": "/images/manali/Atal-Tunnel.png",
    "alt": "The wooden-roofed Atal Tunnel, Rohtang gateway beneath snow-dusted mountains and tall pines",
    "caption": "ATAL TUNNEL, ROHTANG",
    "position": "center 45%",
    "width": 1080,
    "height": 1080,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwT/xAAhEAABAwMEAwAAAAAAAAAAAAABAgMRABIhBAUiMRNBYf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFhEBAQEAAAAAAAAAAAAAAAAAABES/9oADAMBAAIRAxEAPwCkbn43HuJc5A4EDoDs0buvde1DBDZYQCSlUXTiKpIUXEwE2QZJ7B+UmbUi4490tIx//9k="
  },
  "atalGreen": {
    "src": "/images/manali/Gm-4.png",
    "alt": "The Atal Tunnel, Rohtang gateway in the green season, with patches of snow on the peaks behind",
    "caption": "ATAL TUNNEL, IN THE GREEN SEASON",
    "position": "center 50%",
    "width": 1080,
    "height": 1080,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMF/8QAIRAAAgAGAwADAAAAAAAAAAAAAQIAAwQREiEFMXEGQVH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABYRAAMAAAAAAAAAAAAAAAAAAAABEf/aAAwDAQACEQMRAD8AfT8umi6hEP2T1A+Q+QK1Qi0d5mKtdrauQNjyM8UDTAjYM2t5HEHz8ipp5NLNlOVKsB3c2J9EG6SH/9k="
  },
  "sissu": {
    "src": "/images/manali/Sissu.png",
    "alt": "A scooter rounding a curve on a quiet mountain road beside snow-covered slopes dotted with pines",
    "caption": "THE ROAD TOWARDS SISSU",
    "position": "center 60%",
    "width": 1080,
    "height": 1080,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIEBf/EAB8QAAEDBAMBAAAAAAAAAAAAAAIBAxEAEiExBEGxYf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAVEQEBAAAAAAAAAAAAAAAAAAAAEf/aAAwDAQACEQMRAD8A0V5LjYiStKC6aHZrPazpKpVt/Bk8RKmxux989oM8tYKwGyIUhDtxPSUzvKcJsZFu6M7iaQx//9k="
  },
  "peaks": {
    "src": "/images/manali/Manali.png",
    "alt": "A snow-dusted Himalayan ridge glowing blue above dark pines at the edge of a misty valley",
    "caption": "THE RIDGELINE ABOVE MANALI",
    "position": "center 60%",
    "width": 1080,
    "height": 1080,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgME/8QAIhAAAgEDAwUBAAAAAAAAAAAAAQIDAAQRBRIhExUxQlFh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAYEQEBAAMAAAAAAAAAAAAAAAABAAIDMf/aAAwDAQACEQMRAD8ARSatZpkFyWHqFOazprlrICskToP0A0U73bsQGB3ZO5wPPw1WbUIukskZExbgIBzmkGNJdh2//9k="
  },
  "paraglider": {
    "src": "/images/manali/Kullu-Valley.png",
    "alt": "A single paraglider drifting above pine forest, with snow-covered peaks and heavy clouds behind",
    "caption": "A PARAGLIDER OVER THE VALLEY",
    "position": "center 40%",
    "width": 1080,
    "height": 1080,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQQFBv/EACMQAAEDAwIHAAAAAAAAAAAAAAECAxEABAUSURMhIjFBYWL/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABYRAQEBAAAAAAAAAAAAAAAAAAABEf/aAAwDAQACEQMRAD8AvNFRR00XWEKTKyEk7mshZZy5ab0h6R9c6adzyRbTw5djz2PvenZEP//Z"
  },
  "cafe": {
    "src": "/images/cafe.jpeg",
    "alt": "Cafe DO NTHNG at night, its neon sign glowing above a stone entrance with terrace seating and potted plants",
    "caption": "CAFE DO NTHNG, AFTER DARK",
    "position": "center 46%",
    "width": 1272,
    "height": 1189,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAPABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQMG/8QAIRAAAgEEAQUBAAAAAAAAAAAAAQIDAAQRIQUTFCMxUZH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABgRAAIDAAAAAAAAAAAAAAAAAAABAhEh/9oADAMBAAIRAxEAPwDHBSTgDNPcbaXDQW5SOLpFvISQGYZ9fanw9ke7QgKWOgrDVOPBcxOAxRYVI0p1+YqXLaFH/9k="
  },
  "sajla": {
    "src": "/images/packages/sajla/sajla-forest-trail.webp",
    "alt": "Deodar forest, a small bridge and walkers on the trail leading towards Sajla, with green mountain slopes behind",
    "caption": "THE FOREST TRAIL TOWARDS SAJLA",
    "position": "center 60%",
    "credit": {
      "author": "Vinayaraj",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Kanoi_nalha_-Sajla_waterfall_Manali_around_vrtmrgmpksk_(6).jpg"
    },
    "width": 1600,
    "height": 1200,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgMF/8QAHxAAAgICAgMBAAAAAAAAAAAAAQIDEQAEEiETMVFh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAZEQADAAMAAAAAAAAAAAAAAAAAAQIDISL/2gAMAwEAAhEDEQA/AHGIljjHl6r3x7P7WYm6/l3y8YPFaBYJdD7WX09hzBK7hWKdLY9YNudo43CUtkDr5WF5arlkTCWz/9k="
  },
  "sethan": {
    "src": "/images/packages/sethan/sethan-snow-valley.webp",
    "alt": "A wide snow-covered meadow below a granite cliff and a pointed snowy peak at Sethan, with dark conifers on the far slope",
    "caption": "SETHAN, UNDER WINTER SNOW",
    "position": "center 50%",
    "credit": {
      "author": "Catherine Lunaa",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Sethan.jpg"
    },
    "width": 1600,
    "height": 900,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAIF/8QAIhAAAgEDAgcAAAAAAAAAAAAAAQIDABESBCEFIzI0cXKh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABgRAQEBAQEAAAAAAAAAAAAAAAECACEx/9oADAMBAAIRAxEAPwA0T2XOKN5FLb2Qm9Xjrnfk8OYAnYs1h9rWi7dfalDpHimaQ44ZH3f/2Q=="
  },
  "hamta": {
    "src": "/images/packages/hamta/hampta-valley-meadow.webp",
    "alt": "A walker and grazing sheep on a green mountain meadow beneath steep rock walls and forested slopes in Hampta Valley",
    "caption": "HAMPTA VALLEY, IN THE WARMER MONTHS",
    "position": "center 55%",
    "credit": {
      "author": "mkasiak",
      "license": "CC BY 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
      "source": "https://commons.wikimedia.org/wiki/File:Hampta_Valley_-_panoramio.jpg"
    },
    "width": 1600,
    "height": 1158,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAIF/8QAHxAAAgICAgMBAAAAAAAAAAAAAQIDEQAEEjEFIUGx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQP/xAAYEQEAAwEAAAAAAAAAAAAAAAABAAIRA//aAAwDAQACEQMRAD8ADoRQtrqwfi8gNKp+4fZKgSLZ5DoN7o/uaPidKFYleizV9OXswI0N0AT3QAvJHVHCDUTZ/9k="
  },
  "naggarCourtyard": {
    "src": "/images/packages/naggar/naggar-castle-courtyard.webp",
    "alt": "Carved wooden balconies and slate roofs around the courtyard of Naggar Castle, with deodar forest rising behind",
    "caption": "NAGGAR CASTLE, CARVED WOOD & SLATE",
    "position": "center 60%",
    "credit": {
      "author": "Pratishkhedekar",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Naggar_Castle_-_2.jpg"
    },
    "width": 1600,
    "height": 1200,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwUG/8QAJRAAAgECAgsAAAAAAAAAAAAAAQIDAAQFERMhIzEyM1FxgZGh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABYRAQEBAAAAAAAAAAAAAAAAAAAREv/aAAwDAQACEQMRAD8ACxLYdm0AtQwHMJEjE/cvAqnZYrewBdJNDNHv2rhWrLyqkajJFJPUdqFW1cK+qKcv/9k="
  },
  "naggarBalcony": {
    "src": "/images/packages/naggar/naggar-castle-balcony.webp",
    "alt": "A carved timber balcony of Naggar Castle looking out over the green Kullu Valley and misty mountains",
    "caption": "NAGGAR CASTLE, A BALCONY OVER THE VALLEY",
    "position": "center 50%",
    "credit": {
      "author": "Vyacheslav Argenberg",
      "license": "CC BY 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Kullu_Valley,_Naggar_Castle,_India.jpg"
    },
    "width": 1600,
    "height": 1067,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwUG/8QAIRAAAgEDAwUAAAAAAAAAAAAAAQIDABEhBAUSIjFBUbH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABYRAQEBAAAAAAAAAAAAAAAAAAEAEf/aAAwDAQACEQMRAD8AoRbvKi9bjHk1lNXCxkDPMkxYZOb9qdpGYcSbgkfaSRQYiLAW9You0L//2Q=="
  },
  "roerich": {
    "src": "/images/packages/naggar/roerich-estate.webp",
    "alt": "A two-storey wooden house with a white-railed veranda, half hidden by deodars and flowering shrubs, at the Roerich estate in Naggar",
    "caption": "THE ROERICH ESTATE, NAGGAR",
    "position": "center 50%",
    "credit": {
      "author": "Debashritaiitmandi",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Roerich_Art_Gallery_Naggar_DSC01335.jpg"
    },
    "width": 1600,
    "height": 898,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAhEAABAwQBBQAAAAAAAAAAAAABAgMRAAQSEzM0QXFysf/EABUBAQEAAAAAAAAAAAAAAAAAAAED/8QAGBEAAgMAAAAAAAAAAAAAAAAAABEBAiH/2gAMAwEAAhEDEQA/ACNuI2HImVCIJjvQr97U8MBiUESUqmm2/VK9D9qNccz/AJNSizwGf//Z"
  },
  "jana": {
    "src": "/images/packages/jana/jana-waterfall.webp",
    "alt": "A slender waterfall tumbling over moss-covered boulders into a dark, leafy forest pool at Jana",
    "caption": "JANA WATERFALL",
    "position": "center 45%",
    "credit": {
      "author": "AjayParkash",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Jana_Waterfall.jpg"
    },
    "width": 1600,
    "height": 2400,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABADASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAMBAgQG/8QAIhAAAgIBAwQDAAAAAAAAAAAAAQIAAxEEIUEFEhMxIlGh/8QAFgEBAQEAAAAAAAAAAAAAAAAAAQAC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwDlqUayxVrByWAB9CanyrFHHYy7EGR0qkWalBYD4we445xvLdT1K6u82EfIj1wPr8mbNBmhYVi1wRkJsCYi1B4wxxnHEIRT/9k="
  },
  "beas": {
    "src": "/images/packages/kullu-valley/beas-valley-palchan.webp",
    "alt": "The green, orchard-dotted Kullu Valley north of Manali, with a snow-covered Himalayan range under a blue sky",
    "caption": "THE KULLU VALLEY, NORTH OF MANALI",
    "position": "center 55%",
    "credit": {
      "author": "Biswarup Ganguly (derivative: UnpetitproleX)",
      "license": "CC BY 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
      "source": "https://commons.wikimedia.org/wiki/File:Beas_Valley_-_Palchan_-_Kullu_2014-05-10_2279_01.jpg"
    },
    "width": 1600,
    "height": 1067,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwAF/8QAHxABAAEDBAMAAAAAAAAAAAAAAQIAAxEEEiExBRPB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAL/xAAYEQACAwAAAAAAAAAAAAAAAAAAAgEDMf/aAAwDAQACEQMRAD8ASx5TsntGRhkHyq/d00DcXfZJ5wFZFvmeHrFHuZSBeGi3tGETWraf/9k="
  },
  "vashishtTemple": {
    "src": "/images/packages/vashisht/vashisht-temple.webp",
    "alt": "The carved wooden porch and slate-stone roofs of the Vashisht Temple, with a forested hillside rising behind",
    "caption": "VASHISHT TEMPLE, CARVED WOOD & SLATE",
    "position": "center 45%",
    "credit": {
      "author": "Sharvipul",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Vashisht_temple_near_manali.jpg"
    },
    "width": 1600,
    "height": 898,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAEC/8QAJRAAAgECAgsAAAAAAAAAAAAAAQIDAAQFQQYRMTIzNVFyc7HC/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABYRAQEBAAAAAAAAAAAAAAAAAAEAAv/aAAwDAQACEQMRAD8AlxpTPLZsFhAUje6jXQZMevDDG7SMyNsUZjOtnlCeRvmgzcODtf3RdJMyX//Z"
  },
  "hotSpring": {
    "src": "/images/packages/vashisht/vashisht-hot-spring-baths.webp",
    "alt": "A stone-walled bathing tank at the Vashisht hot-water spring, with a carved stone spout set into the old wall",
    "caption": "THE VASHISHT HOT-WATER SPRING BATHS",
    "position": "center 55%",
    "credit": {
      "author": "John Hill",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Hot_Springs_near_Manali._2020.jpg"
    },
    "width": 1024,
    "height": 768,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwEG/8QAHxAAAgICAgMBAAAAAAAAAAAAAQIDEQAEEiETIjFh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAWEQEBAQAAAAAAAAAAAAAAAAABAAL/2gAMAwEAAhEDEQA/AFiZSnZPjjWzJzvvLuBI4Sx5shF2X6+Xme1tiYxuDNJXqK5GsbYBEYPJyf1jkmYW/9k="
  },
  "manuTemple": {
    "src": "/images/packages/old-manali/manu-temple.webp",
    "alt": "The tiered timber roof and white stone tower of the Manu Temple in Old Manali, seen against a blue sky",
    "caption": "MANU TEMPLE, OLD MANALI",
    "position": "center 40%",
    "credit": {
      "author": "Birte Fritsch",
      "license": "CC BY 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Birte_Fritsch,_Manu_Temple_in_Old_Manali_(45).jpg"
    },
    "width": 1600,
    "height": 1063,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAALABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQH/xAAkEAABAwMDBAMAAAAAAAAAAAACAQMRAAQTBSFBEjEyQlGRsf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAGBEBAAMBAAAAAAAAAAAAAAAAAQADEQL/2gAMAwEAAhEDEQA/AFdevCtmAVnHnJfdU8eV/KNt9QS5t0zmyDkxCF3+6CzuXJIb5q4UxJb/ADUJoOpYFE242oWPLK16ZP/Z"
  },
  "dhungri": {
    "src": "/images/packages/dhungri/cedar-forest-hadimba.webp",
    "alt": "Tall deodar trees rising into a misty sky in the cedar forest around Hadimba Devi Temple, with visitors on the path below",
    "caption": "THE DEODARS AROUND HADIMBA",
    "position": "center 30%",
    "credit": {
      "author": "TheSlumPanda",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Cedar_Forest_around_Hadimba_Devi_Temple,_Manali.jpg"
    },
    "width": 1100,
    "height": 1467,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAVABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAEDBf/EACEQAAIBAwUAAwAAAAAAAAAAAAECEQADMQQTIUGhEuHw/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAEC/8QAGBEBAAMBAAAAAAAAAAAAAAAAAAECEUH/2gAMAwEAAhEDEQA/AJaXU7t13DMsKePlEfWKY1Dm1ZtXTKFj1xn2s9XGy7SAxjrr8BRugqobkIcHGaaJBFCEmTBBz5SUq6sQgEUUVON2jJf/2Q=="
  },
  "sissuFalls": {
    "src": "/images/packages/sissu/sissu-waterfall.webp",
    "alt": "A thin waterfall dropping down a dark cliff into a green Lahaul valley, seen from the road near Sissu",
    "caption": "THE WATERFALL ABOVE SISSU",
    "position": "center 35%",
    "credit": {
      "author": "Lalitgupta isgec",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Sissu_Water_Fall.jpg"
    },
    "width": 1600,
    "height": 1200,
    "blur": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwQF/8QAHxABAAIBAwUAAAAAAAAAAAAAAQIDAAQRISIjMYGh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABYRAQEBAAAAAAAAAAAAAAAAAAARIf/aAAwDAQACEQMRAD8AktquO7YyZLyzF+4Fk5r1z8cG+bwpg26emZvOuL6x0x//2Q=="
  }
};
