// Reads scripts/package-images.json and writes lib/packageImages.generated.ts with each image's intrinsic size and a tiny blur
// placeholder, so the journeys pages can use next/image `placeholder="blur"` like the rest of the site. Run: npm run package-images
import sharp from 'sharp';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const root = resolve(import.meta.dirname, '..');
const catalog = JSON.parse(readFileSync(resolve(root, 'scripts/package-images.json'), 'utf8'));
const out = {};
for (const [key, entry] of Object.entries(catalog)) {
  const file = resolve(root, 'public', entry.src.replace(/^\//, ''));
  const meta = await sharp(file).metadata();
  const swap = meta.orientation && meta.orientation >= 5;
  const blur = await sharp(file).rotate().resize(16).jpeg({ quality: 40 }).toBuffer();
  out[key] = { ...entry, width: swap ? meta.height : meta.width, height: swap ? meta.width : meta.height, blur: `data:image/jpeg;base64,${blur.toString('base64')}` };
}
const keys = Object.keys(out).map(k => `'${k}'`).join(' | ');
writeFileSync(resolve(root, 'lib/packageImages.generated.ts'), `// AUTO-GENERATED by scripts/package-images.mjs from scripts/package-images.json. Do not edit by hand; run \`npm run package-images\`.
export type PackageImageCredit = { author: string; license: string; licenseUrl: string; source: string };
export type PackageImageKey = ${keys};
export type PackageImageData = { src: string; alt: string; caption: string; position: string; width: number; height: number; blur: string; credit?: PackageImageCredit };
export const packageImages: Record<PackageImageKey, PackageImageData> = ${JSON.stringify(out, null, 2)};
`);
console.log('wrote lib/packageImages.generated.ts for', Object.keys(out).length, 'images');
